
K
findbugs:UC_USELESS_VOID_METHOD(
findbugsUC_USELESS_VOID_METHODINFO
’
Bfindbugs:DMI_SCHEDULED_THREAD_POOL_EXECUTOR_WITH_ZERO_CORE_THREADSL
findbugs9DMI_SCHEDULED_THREAD_POOL_EXECUTOR_WITH_ZERO_CORE_THREADSMAJOR
Z
&findbugs:IM_MULTIPLYING_RESULT_OF_IREM0
findbugsIM_MULTIPLYING_RESULT_OF_IREMMAJOR
B
findbugs:NM_LCASE_HASHCODE$
findbugsNM_LCASE_HASHCODEMAJOR
r
2findbugs:ODR_OPEN_DATABASE_RESOURCE_EXCEPTION_PATH<
findbugs)ODR_OPEN_DATABASE_RESOURCE_EXCEPTION_PATHMAJOR
T
#findbugs:LI_LAZY_INIT_UPDATE_STATIC-
findbugsLI_LAZY_INIT_UPDATE_STATICMAJOR
_
)findbugs:MS_MUTABLE_COLLECTION_PKGPROTECT2
findbugs MS_MUTABLE_COLLECTION_PKGPROTECTINFO
v
4findbugs:WL_USING_GETCLASS_RATHER_THAN_CLASS_LITERAL>
findbugs+WL_USING_GETCLASS_RATHER_THAN_CLASS_LITERALMAJOR
¶
Tfindbugs:DMI_FUTILE_ATTEMPT_TO_CHANGE_MAXPOOL_SIZE_OF_SCHEDULED_THREAD_POOL_EXECUTOR^
findbugsKDMI_FUTILE_ATTEMPT_TO_CHANGE_MAXPOOL_SIZE_OF_SCHEDULED_THREAD_POOL_EXECUTORMAJOR
H
findbugs:IJU_BAD_SUITE_METHOD'
findbugsIJU_BAD_SUITE_METHODMAJOR
[
'findbugs:NS_DANGEROUS_NON_SHORT_CIRCUIT0
findbugsNS_DANGEROUS_NON_SHORT_CIRCUITINFO
D
findbugs:EQ_SELF_USE_OBJECT%
findbugsEQ_SELF_USE_OBJECTMAJOR
_
)findbugs:RV_DONT_JUST_NULL_CHECK_READLINE2
findbugs RV_DONT_JUST_NULL_CHECK_READLINEINFO
O
!findbugs:SA_LOCAL_SELF_ASSIGNMENT*
findbugsSA_LOCAL_SELF_ASSIGNMENTINFO
.
findbugs:BIT_AND
findbugsBIT_ANDMAJOR
H
findbugs:NP_NULL_ON_SOME_PATH'
findbugsNP_NULL_ON_SOME_PATHMAJOR
€
9findbugs:RE_CANT_USE_FILE_SEPARATOR_AS_REGULAR_EXPRESSIONC
findbugs0RE_CANT_USE_FILE_SEPARATOR_AS_REGULAR_EXPRESSIONMAJOR
<
findbugs:DM_NUMBER_CTOR!
findbugsDM_NUMBER_CTORMAJOR
R
"findbugs:FI_FINALIZER_NULLS_FIELDS,
findbugsFI_FINALIZER_NULLS_FIELDSMAJOR
A
findbugs:MS_OOI_PKGPROTECT#
findbugsMS_OOI_PKGPROTECTINFO
\
'findbugs:STCAL_STATIC_CALENDAR_INSTANCE1
findbugsSTCAL_STATIC_CALENDAR_INSTANCEMAJOR
E
findbugs:BC_UNCONFIRMED_CAST%
findbugsBC_UNCONFIRMED_CASTINFO
o
1findbugs:RCN_REDUNDANT_COMPARISON_TWO_NULL_VALUES:
findbugs(RCN_REDUNDANT_COMPARISON_TWO_NULL_VALUESINFO
i
.findbugs:RCN_REDUNDANT_NULLCHECK_OF_NULL_VALUE7
findbugs%RCN_REDUNDANT_NULLCHECK_OF_NULL_VALUEINFO
K
findbugs:DMI_UNSUPPORTED_METHOD(
findbugsDMI_UNSUPPORTED_METHODINFO
8
findbugs:NM_CONFUSING
findbugsNM_CONFUSINGMAJOR
r
2findbugs:NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS<
findbugs)NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUSMAJOR
Š
>findbugs:TQ_COMPARING_VALUES_WITH_INCOMPATIBLE_TYPE_QUALIFIERSH
findbugs5TQ_COMPARING_VALUES_WITH_INCOMPATIBLE_TYPE_QUALIFIERSMAJOR
J
findbugs:ME_MUTABLE_ENUM_FIELD(
findbugsME_MUTABLE_ENUM_FIELDMAJOR
J
findbugs:MF_METHOD_MASKS_FIELD(
findbugsMF_METHOD_MASKS_FIELDMAJOR
…
<findbugs:NP_PARAMETER_MUST_BE_NONNULL_BUT_MARKED_AS_NULLABLEE
findbugs3NP_PARAMETER_MUST_BE_NONNULL_BUT_MARKED_AS_NULLABLEINFO
*
findbugs:DM_GC
findbugsDM_GCMAJOR
@
findbugs:NM_WRONG_PACKAGE#
findbugsNM_WRONG_PACKAGEMAJOR
`
)findbugs:STI_INTERRUPTED_ON_CURRENTTHREAD3
findbugs STI_INTERRUPTED_ON_CURRENTTHREADMAJOR
F
findbugs:TLW_TWO_LOCK_NOTIFY&
findbugsTLW_TWO_LOCK_NOTIFYMAJOR
U
$findbugs:USM_USELESS_SUBCLASS_METHOD-
findbugsUSM_USELESS_SUBCLASS_METHODINFO
g
-findbugs:UUF_UNUSED_PUBLIC_OR_PROTECTED_FIELD6
findbugs$UUF_UNUSED_PUBLIC_OR_PROTECTED_FIELDINFO
^
(findbugs:HSC_HUGE_SHARED_STRING_CONSTANT2
findbugsHSC_HUGE_SHARED_STRING_CONSTANTMAJOR
h
-findbugs:IIL_PATTERN_COMPILE_IN_LOOP_INDIRECT7
findbugs$IIL_PATTERN_COMPILE_IN_LOOP_INDIRECTMAJOR
n
0findbugs:SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH:
findbugs'SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGHMAJOR
L
findbugs:FI_EXPLICIT_INVOCATION)
findbugsFI_EXPLICIT_INVOCATIONMAJOR
Z
&findbugs:FL_MATH_USING_FLOAT_PRECISION0
findbugsFL_MATH_USING_FLOAT_PRECISIONMAJOR
V
$findbugs:ICAST_INT_2_LONG_AS_INSTANT.
findbugsICAST_INT_2_LONG_AS_INSTANTMAJOR
x
5findbugs:UR_UNINIT_READ_CALLED_FROM_SUPER_CONSTRUCTOR?
findbugs,UR_UNINIT_READ_CALLED_FROM_SUPER_CONSTRUCTORMAJOR
V
$findbugs:FB_MISSING_EXPECTED_WARNING.
findbugsFB_MISSING_EXPECTED_WARNINGMAJOR
z
6findbugs:RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE@
findbugs-RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPEMAJOR
@
findbugs:URF_UNREAD_FIELD#
findbugsURF_UNREAD_FIELDMAJOR
>
findbugs:DE_MIGHT_IGNORE"
findbugsDE_MIGHT_IGNOREMAJOR
R
"findbugs:DM_RUN_FINALIZERS_ON_EXIT,
findbugsDM_RUN_FINALIZERS_ON_EXITMAJOR
r
2findbugs:IJU_ASSERT_METHOD_INVOKED_FROM_RUN_METHOD<
findbugs)IJU_ASSERT_METHOD_INVOKED_FROM_RUN_METHODMAJOR
f
,findbugs:INT_BAD_COMPARISON_WITH_SIGNED_BYTE6
findbugs#INT_BAD_COMPARISON_WITH_SIGNED_BYTEMAJOR
Q
"findbugs:CAA_COVARIANT_ARRAY_FIELD+
findbugsCAA_COVARIANT_ARRAY_FIELDINFO
P
!findbugs:NP_ALWAYS_NULL_EXCEPTION+
findbugsNP_ALWAYS_NULL_EXCEPTIONMAJOR
S
#findbugs:SA_FIELD_DOUBLE_ASSIGNMENT,
findbugsSA_FIELD_DOUBLE_ASSIGNMENTINFO
[
'findbugs:DLS_DEAD_LOCAL_STORE_IN_RETURN0
findbugsDLS_DEAD_LOCAL_STORE_IN_RETURNINFO
\
'findbugs:DMI_INVOKING_TOSTRING_ON_ARRAY1
findbugsDMI_INVOKING_TOSTRING_ON_ARRAYMAJOR
P
!findbugs:SWL_SLEEP_WITH_LOCK_HELD+
findbugsSWL_SLEEP_WITH_LOCK_HELDMAJOR
V
$findbugs:UPM_UNCALLED_PRIVATE_METHOD.
findbugsUPM_UNCALLED_PRIVATE_METHODMAJOR
O
findbugs:BC_IMPOSSIBLE_DOWNCAST,
findbugsBC_IMPOSSIBLE_DOWNCASTCRITICAL
b
*findbugs:GC_UNCHECKED_TYPE_IN_GENERIC_CALL4
findbugs!GC_UNCHECKED_TYPE_IN_GENERIC_CALLMAJOR
h
-findbugs:IO_APPENDING_TO_OBJECT_OUTPUT_STREAM7
findbugs$IO_APPENDING_TO_OBJECT_OUTPUT_STREAMMAJOR
C
findbugs:MS_CANNOT_BE_FINAL$
findbugsMS_CANNOT_BE_FINALINFO
R
"findbugs:NP_ARGUMENT_MIGHT_BE_NULL,
findbugsNP_ARGUMENT_MIGHT_BE_NULLMAJOR
V
$findbugs:SE_NONFINAL_SERIALVERSIONID.
findbugsSE_NONFINAL_SERIALVERSIONIDMAJOR
\
'findbugs:EQ_COMPARETO_USE_OBJECT_EQUALS1
findbugsEQ_COMPARETO_USE_OBJECT_EQUALSMAJOR
\
'findbugs:EQ_DONT_DEFINE_EQUALS_FOR_ENUM1
findbugsEQ_DONT_DEFINE_EQUALS_FOR_ENUMMAJOR
O
!findbugs:QF_QUESTIONABLE_FOR_LOOP*
findbugsQF_QUESTIONABLE_FOR_LOOPINFO
j
.findbugs:DL_SYNCHRONIZATION_ON_BOXED_PRIMITIVE8
findbugs%DL_SYNCHRONIZATION_ON_BOXED_PRIMITIVEMAJOR
D
findbugs:DM_STRING_TOSTRING%
findbugsDM_STRING_TOSTRINGMAJOR
B
findbugs:RC_REF_COMPARISON$
findbugsRC_REF_COMPARISONMAJOR
4
findbugs:BIT_AND_ZZ
findbugs
BIT_AND_ZZMAJOR
V
$findbugs:DM_BOXED_PRIMITIVE_TOSTRING.
findbugsDM_BOXED_PRIMITIVE_TOSTRINGMAJOR
j
.findbugs:SIC_INNER_SHOULD_BE_STATIC_NEEDS_THIS8
findbugs%SIC_INNER_SHOULD_BE_STATIC_NEEDS_THISMAJOR
\
'findbugs:EQ_GETCLASS_AND_CLASS_CONSTANT1
findbugsEQ_GETCLASS_AND_CLASS_CONSTANTMAJOR
V
$findbugs:NP_NONNULL_RETURN_VIOLATION.
findbugsNP_NONNULL_RETURN_VIOLATIONMAJOR
Z
&findbugs:NP_TOSTRING_COULD_RETURN_NULL0
findbugsNP_TOSTRING_COULD_RETURN_NULLMAJOR
k
/findbugs:RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT8
findbugs&RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECTINFO
Q
"findbugs:ICAST_IDIV_CAST_TO_DOUBLE+
findbugsICAST_IDIV_CAST_TO_DOUBLEINFO
`
)findbugs:NM_SAME_SIMPLE_NAME_AS_INTERFACE3
findbugs NM_SAME_SIMPLE_NAME_AS_INTERFACEMAJOR
D
findbugs:SE_BAD_FIELD_STORE%
findbugsSE_BAD_FIELD_STOREMAJOR
Z
&findbugs:EC_INCOMPATIBLE_ARRAY_COMPARE0
findbugsEC_INCOMPATIBLE_ARRAY_COMPAREMAJOR
‡
=findbugs:IA_AMBIGUOUS_INVOCATION_OF_INHERITED_OR_OUTER_METHODF
findbugs4IA_AMBIGUOUS_INVOCATION_OF_INHERITED_OR_OUTER_METHODINFO
Z
&findbugs:OS_OPEN_STREAM_EXCEPTION_PATH0
findbugsOS_OPEN_STREAM_EXCEPTION_PATHMAJOR
…
<findbugs:TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_NEVER_SINKE
findbugs3TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_NEVER_SINKINFO
R
"findbugs:DLS_OVERWRITTEN_INCREMENT,
findbugsDLS_OVERWRITTEN_INCREMENTMAJOR
<
findbugs:EQ_ALWAYS_TRUE!
findbugsEQ_ALWAYS_TRUEMAJOR
~
8findbugs:NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTORB
findbugs/NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTORMAJOR
D
findbugs:NP_NULL_INSTANCEOF%
findbugsNP_NULL_INSTANCEOFMAJOR
B
findbugs:DM_USELESS_THREAD$
findbugsDM_USELESS_THREADMAJOR
`
)findbugs:EC_UNRELATED_CLASS_AND_INTERFACE3
findbugs EC_UNRELATED_CLASS_AND_INTERFACEMAJOR
J
findbugs:FI_MISSING_SUPER_CALL(
findbugsFI_MISSING_SUPER_CALLMAJOR
H
findbugs:EC_BAD_ARRAY_COMPARE'
findbugsEC_BAD_ARRAY_COMPAREMAJOR
J
findbugs:HE_EQUALS_NO_HASHCODE(
findbugsHE_EQUALS_NO_HASHCODEMAJOR
@
findbugs:CO_ABSTRACT_SELF#
findbugsCO_ABSTRACT_SELFMAJOR
J
findbugs:EC_ARRAY_AND_NONARRAY(
findbugsEC_ARRAY_AND_NONARRAYMAJOR
^
(findbugs:HE_INHERITS_EQUALS_USE_HASHCODE2
findbugsHE_INHERITS_EQUALS_USE_HASHCODEMAJOR
T
#findbugs:NP_CLONE_COULD_RETURN_NULL-
findbugsNP_CLONE_COULD_RETURN_NULLMAJOR
T
#findbugs:SE_NONLONG_SERIALVERSIONID-
findbugsSE_NONLONG_SERIALVERSIONIDMAJOR
P
!findbugs:SQL_BAD_RESULTSET_ACCESS+
findbugsSQL_BAD_RESULTSET_ACCESSMAJOR
>
findbugs:NN_NAKED_NOTIFY"
findbugsNN_NAKED_NOTIFYMAJOR
h
-findbugs:SE_COMPARATOR_SHOULD_BE_SERIALIZABLE7
findbugs$SE_COMPARATOR_SHOULD_BE_SERIALIZABLEMAJOR
O
!findbugs:UCF_USELESS_CONTROL_FLOW*
findbugsUCF_USELESS_CONTROL_FLOWINFO
L
findbugs:DMI_COLLECTION_OF_URLS)
findbugsDMI_COLLECTION_OF_URLSMAJOR
r
2findbugs:SA_LOCAL_SELF_ASSIGNMENT_INSTEAD_OF_FIELD<
findbugs)SA_LOCAL_SELF_ASSIGNMENT_INSTEAD_OF_FIELDMAJOR
t
3findbugs:VA_PRIMITIVE_ARRAY_PASSED_TO_OBJECT_VARARG=
findbugs*VA_PRIMITIVE_ARRAY_PASSED_TO_OBJECT_VARARGMAJOR
D
findbugs:BC_NULL_INSTANCEOF%
findbugsBC_NULL_INSTANCEOFMAJOR
Z
&findbugs:IIL_PREPARE_STATEMENT_IN_LOOP0
findbugsIIL_PREPARE_STATEMENT_IN_LOOPMAJOR
p
1findbugs:SW_SWING_METHODS_INVOKED_IN_SWING_THREAD;
findbugs(SW_SWING_METHODS_INVOKED_IN_SWING_THREADMAJOR
E
findbugs:RANGE_ARRAY_INDEX'
findbugsRANGE_ARRAY_INDEXCRITICAL
p
1findbugs:STCAL_INVOKE_ON_STATIC_CALENDAR_INSTANCE;
findbugs(STCAL_INVOKE_ON_STATIC_CALENDAR_INSTANCEMAJOR
j
.findbugs:CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE8
findbugs%CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLEMAJOR
.
findbugs:DM_EXIT
findbugsDM_EXITMAJOR
Z
&findbugs:HE_HASHCODE_USE_OBJECT_EQUALS0
findbugsHE_HASHCODE_USE_OBJECT_EQUALSMAJOR
H
findbugs:IJU_SUITE_NOT_STATIC'
findbugsIJU_SUITE_NOT_STATICMAJOR
R
"findbugs:BIT_SIGNED_CHECK_HIGH_BIT,
findbugsBIT_SIGNED_CHECK_HIGH_BITMAJOR
?
findbugs:INT_BAD_REM_BY_1"
findbugsINT_BAD_REM_BY_1INFO
Z
&findbugs:RpC_REPEATED_CONDITIONAL_TEST0
findbugsRpC_REPEATED_CONDITIONAL_TESTMAJOR
‚
:findbugs:BX_BOXING_IMMEDIATELY_UNBOXED_TO_PERFORM_COERCIOND
findbugs1BX_BOXING_IMMEDIATELY_UNBOXED_TO_PERFORM_COERCIONMAJOR
l
/findbugs:DMI_BIGDECIMAL_CONSTRUCTED_FROM_DOUBLE9
findbugs&DMI_BIGDECIMAL_CONSTRUCTED_FROM_DOUBLEMAJOR
S
#findbugs:DP_DO_INSIDE_DO_PRIVILEGED,
findbugsDP_DO_INSIDE_DO_PRIVILEGEDINFO
X
%findbugs:JLM_JSR166_LOCK_MONITORENTER/
findbugsJLM_JSR166_LOCK_MONITORENTERMAJOR
T
#findbugs:PT_RELATIVE_PATH_TRAVERSAL-
findbugsPT_RELATIVE_PATH_TRAVERSALMAJOR
:
findbugs:RU_INVOKE_RUN 
findbugsRU_INVOKE_RUNMAJOR
B
findbugs:TLW_TWO_LOCK_WAIT$
findbugsTLW_TWO_LOCK_WAITMAJOR
H
findbugs:IS_FIELD_NOT_GUARDED'
findbugsIS_FIELD_NOT_GUARDEDMAJOR
E
findbugs:MS_FINAL_PKGPROTECT%
findbugsMS_FINAL_PKGPROTECTINFO
8
findbugs:SE_BAD_FIELD
findbugsSE_BAD_FIELDMAJOR
e
,findbugs:BC_UNCONFIRMED_CAST_OF_RETURN_VALUE5
findbugs#BC_UNCONFIRMED_CAST_OF_RETURN_VALUEINFO
d
+findbugs:SI_INSTANCE_BEFORE_FINALS_ASSIGNED5
findbugs"SI_INSTANCE_BEFORE_FINALS_ASSIGNEDMAJOR
X
%findbugs:BOA_BADLY_OVERRIDDEN_ADAPTER/
findbugsBOA_BADLY_OVERRIDDEN_ADAPTERMAJOR
Z
&findbugs:BX_BOXING_IMMEDIATELY_UNBOXED0
findbugsBX_BOXING_IMMEDIATELY_UNBOXEDMAJOR
`
)findbugs:DMI_VACUOUS_SELF_COLLECTION_CALL3
findbugs DMI_VACUOUS_SELF_COLLECTION_CALLMAJOR
b
*findbugs:UI_INHERITANCE_UNSAFE_GETRESOURCE4
findbugs!UI_INHERITANCE_UNSAFE_GETRESOURCEMAJOR
\
'findbugs:NP_NULL_PARAM_DEREF_NONVIRTUAL1
findbugsNP_NULL_PARAM_DEREF_NONVIRTUALMAJOR
x
5findbugs:RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUE?
findbugs,RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUEMAJOR
|
7findbugs:DL_SYNCHRONIZATION_ON_UNSHARED_BOXED_PRIMITIVEA
findbugs.DL_SYNCHRONIZATION_ON_UNSHARED_BOXED_PRIMITIVEMAJOR
l
/findbugs:DMI_LONG_BITS_TO_DOUBLE_INVOKED_ON_INT9
findbugs&DMI_LONG_BITS_TO_DOUBLE_INVOKED_ON_INTMAJOR
P
!findbugs:EQ_COMPARING_CLASS_NAMES+
findbugsEQ_COMPARING_CLASS_NAMESMAJOR
p
1findbugs:DMI_INVOKING_TOSTRING_ON_ANONYMOUS_ARRAY;
findbugs(DMI_INVOKING_TOSTRING_ON_ANONYMOUS_ARRAYMAJOR
>
findbugs:NP_CLOSING_NULL"
findbugsNP_CLOSING_NULLMAJOR
r
2findbugs:TQ_MAYBE_SOURCE_VALUE_REACHES_ALWAYS_SINK<
findbugs)TQ_MAYBE_SOURCE_VALUE_REACHES_ALWAYS_SINKMAJOR
6
findbugs:EC_NULL_ARG
findbugsEC_NULL_ARGMAJOR
I
findbugs:EI_EXPOSE_STATIC_REP2'
findbugsEI_EXPOSE_STATIC_REP2INFO
G
findbugs:PS_PUBLIC_SEMAPHORES&
findbugsPS_PUBLIC_SEMAPHORESINFO
G
findbugs:BC_IMPOSSIBLE_CAST(
findbugsBC_IMPOSSIBLE_CASTCRITICAL
@
findbugs:EQ_ABSTRACT_SELF#
findbugsEQ_ABSTRACT_SELFMAJOR
Z
&findbugs:IIO_INEFFICIENT_LAST_INDEX_OF0
findbugsIIO_INEFFICIENT_LAST_INDEX_OFMAJOR
G
findbugs:SF_SWITCH_NO_DEFAULT&
findbugsSF_SWITCH_NO_DEFAULTINFO
P
!findbugs:ML_SYNC_ON_UPDATED_FIELD+
findbugsML_SYNC_ON_UPDATED_FIELDMAJOR
m
0findbugs:ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD9
findbugs'ST_WRITE_TO_STATIC_FROM_INSTANCE_METHODINFO
@
findbugs:UUF_UNUSED_FIELD#
findbugsUUF_UNUSED_FIELDMAJOR
9
findbugs:MS_EXPOSE_REP
findbugsMS_EXPOSE_REPINFO
8
findbugs:NM_BAD_EQUAL
findbugsNM_BAD_EQUALMAJOR
k
/findbugs:NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE8
findbugs&NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUEINFO
l
/findbugs:RC_REF_COMPARISON_BAD_PRACTICE_BOOLEAN9
findbugs&RC_REF_COMPARISON_BAD_PRACTICE_BOOLEANMAJOR
Z
&findbugs:IMA_INEFFICIENT_MEMBER_ACCESS0
findbugsIMA_INEFFICIENT_MEMBER_ACCESSMAJOR
G
findbugs:RV_REM_OF_RANDOM_INT&
findbugsRV_REM_OF_RANDOM_INTINFO
f
,findbugs:XSS_REQUEST_PARAMETER_TO_SEND_ERROR6
findbugs#XSS_REQUEST_PARAMETER_TO_SEND_ERRORMAJOR
c
+findbugs:DMI_NONSERIALIZABLE_OBJECT_WRITTEN4
findbugs"DMI_NONSERIALIZABLE_OBJECT_WRITTENINFO
N
 findbugs:EC_UNRELATED_INTERFACES*
findbugsEC_UNRELATED_INTERFACESMAJOR
^
(findbugs:NM_METHOD_CONSTRUCTOR_CONFUSION2
findbugsNM_METHOD_CONSTRUCTOR_CONFUSIONMAJOR
^
(findbugs:AM_CREATES_EMPTY_ZIP_FILE_ENTRY2
findbugsAM_CREATES_EMPTY_ZIP_FILE_ENTRYMAJOR
@
findbugs:BIT_SIGNED_CHECK#
findbugsBIT_SIGNED_CHECKMAJOR
G
findbugs:NS_NON_SHORT_CIRCUIT&
findbugsNS_NON_SHORT_CIRCUITINFO
g
+findbugs:BC_IMPOSSIBLE_CAST_PRIMITIVE_ARRAY8
findbugs"BC_IMPOSSIBLE_CAST_PRIMITIVE_ARRAYCRITICAL
I
findbugs:DB_DUPLICATE_BRANCHES'
findbugsDB_DUPLICATE_BRANCHESINFO
]
(findbugs:DMI_HARDCODED_ABSOLUTE_FILENAME1
findbugsDMI_HARDCODED_ABSOLUTE_FILENAMEINFO
F
findbugs:UWF_UNWRITTEN_FIELD&
findbugsUWF_UNWRITTEN_FIELDMAJOR
F
findbugs:DM_NEW_FOR_GETCLASS&
findbugsDM_NEW_FOR_GETCLASSMAJOR
G
findbugs:RANGE_ARRAY_OFFSET(
findbugsRANGE_ARRAY_OFFSETCRITICAL
D
findbugs:EC_UNRELATED_TYPES%
findbugsEC_UNRELATED_TYPESMAJOR
\
'findbugs:SIC_THREADLOCAL_DEADLY_EMBRACE1
findbugsSIC_THREADLOCAL_DEADLY_EMBRACEMAJOR
^
(findbugs:VA_FORMAT_STRING_BAD_CONVERSION2
findbugsVA_FORMAT_STRING_BAD_CONVERSIONMAJOR
t
3findbugs:VA_FORMAT_STRING_BAD_CONVERSION_FROM_ARRAY=
findbugs*VA_FORMAT_STRING_BAD_CONVERSION_FROM_ARRAYMAJOR
E
findbugs:DM_DEFAULT_ENCODING%
findbugsDM_DEFAULT_ENCODINGINFO
J
findbugs:LI_LAZY_INIT_INSTANCE(
findbugsLI_LAZY_INIT_INSTANCEMAJOR
g
-findbugs:URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD6
findbugs$URF_UNREAD_PUBLIC_OR_PROTECTED_FIELDINFO
<
findbugs:UWF_NULL_FIELD!
findbugsUWF_NULL_FIELDMAJOR
S
#findbugs:FE_FLOATING_POINT_EQUALITY,
findbugsFE_FLOATING_POINT_EQUALITYINFO
Q
"findbugs:INT_VACUOUS_BIT_OPERATION+
findbugsINT_VACUOUS_BIT_OPERATIONINFO
b
*findbugs:UL_UNRELEASED_LOCK_EXCEPTION_PATH4
findbugs!UL_UNRELEASED_LOCK_EXCEPTION_PATHMAJOR
R
"findbugs:MSF_MUTABLE_SERVLET_FIELD,
findbugsMSF_MUTABLE_SERVLET_FIELDMAJOR
X
%findbugs:NM_WRONG_PACKAGE_INTENTIONAL/
findbugsNM_WRONG_PACKAGE_INTENTIONALMAJOR
o
1findbugs:NP_NULL_ON_SOME_PATH_MIGHT_BE_INFEASIBLE:
findbugs(NP_NULL_ON_SOME_PATH_MIGHT_BE_INFEASIBLEINFO
^
(findbugs:HRS_REQUEST_PARAMETER_TO_COOKIE2
findbugsHRS_REQUEST_PARAMETER_TO_COOKIEMAJOR
V
$findbugs:IIL_PATTERN_COMPILE_IN_LOOP.
findbugsIIL_PATTERN_COMPILE_IN_LOOPMAJOR
b
*findbugs:NM_SAME_SIMPLE_NAME_AS_SUPERCLASS4
findbugs!NM_SAME_SIMPLE_NAME_AS_SUPERCLASSMAJOR
I
findbugs:SF_SWITCH_FALLTHROUGH'
findbugsSF_SWITCH_FALLTHROUGHINFO
j
.findbugs:NP_GUARANTEED_DEREF_ON_EXCEPTION_PATH8
findbugs%NP_GUARANTEED_DEREF_ON_EXCEPTION_PATHMAJOR
s
3findbugs:VA_FORMAT_STRING_BAD_CONVERSION_TO_BOOLEAN<
findbugs*VA_FORMAT_STRING_BAD_CONVERSION_TO_BOOLEANINFO
P
!findbugs:DC_PARTIALLY_CONSTRUCTED+
findbugsDC_PARTIALLY_CONSTRUCTEDMAJOR
[
'findbugs:PZLA_PREFER_ZERO_LENGTH_ARRAYS0
findbugsPZLA_PREFER_ZERO_LENGTH_ARRAYSINFO
b
*findbugs:SQL_BAD_PREPARED_STATEMENT_ACCESS4
findbugs!SQL_BAD_PREPARED_STATEMENT_ACCESSMAJOR
D
findbugs:RS_READOBJECT_SYNC%
findbugsRS_READOBJECT_SYNCMAJOR
N
 findbugs:RV_RETURN_VALUE_IGNORED*
findbugsRV_RETURN_VALUE_IGNOREDMAJOR
r
2findbugs:UMAC_UNCALLABLE_METHOD_OF_ANONYMOUS_CLASS<
findbugs)UMAC_UNCALLABLE_METHOD_OF_ANONYMOUS_CLASSMAJOR
4
findbugs:FI_USELESS
findbugs
FI_USELESSMAJOR
<
findbugs:RR_NOT_CHECKED!
findbugsRR_NOT_CHECKEDMAJOR
<
findbugs:SR_NOT_CHECKED!
findbugsSR_NOT_CHECKEDMAJOR
\
'findbugs:CO_COMPARETO_RESULTS_MIN_VALUE1
findbugsCO_COMPARETO_RESULTS_MIN_VALUEMAJOR
r
2findbugs:EC_UNRELATED_TYPES_USING_POINTER_EQUALITY<
findbugs)EC_UNRELATED_TYPES_USING_POINTER_EQUALITYMAJOR
D
findbugs:NP_UNWRITTEN_FIELD%
findbugsNP_UNWRITTEN_FIELDMAJOR
R
"findbugs:DMI_ARGUMENTS_WRONG_ORDER,
findbugsDMI_ARGUMENTS_WRONG_ORDERMAJOR
P
!findbugs:DMI_CONSTANT_DB_PASSWORD+
findbugsDMI_CONSTANT_DB_PASSWORDMAJOR
D
findbugs:EQ_OTHER_NO_OBJECT%
findbugsEQ_OTHER_NO_OBJECTMAJOR
T
#findbugs:BAC_BAD_APPLET_CONSTRUCTOR-
findbugsBAC_BAD_APPLET_CONSTRUCTORMAJOR
F
findbugs:DM_STRING_VOID_CTOR&
findbugsDM_STRING_VOID_CTORMAJOR
h
-findbugs:HRS_REQUEST_PARAMETER_TO_HTTP_HEADER7
findbugs$HRS_REQUEST_PARAMETER_TO_HTTP_HEADERMAJOR
j
.findbugs:NP_EQUALS_SHOULD_HANDLE_NULL_ARGUMENT8
findbugs%NP_EQUALS_SHOULD_HANDLE_NULL_ARGUMENTMAJOR
^
(findbugs:SIC_INNER_SHOULD_BE_STATIC_ANON2
findbugsSIC_INNER_SHOULD_BE_STATIC_ANONMAJOR
K
findbugs:XFB_XML_FACTORY_BYPASS(
findbugsXFB_XML_FACTORY_BYPASSINFO
s
3findbugs:DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED<
findbugs*DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGEDINFO
G
findbugs:RANGE_STRING_INDEX(
findbugsRANGE_STRING_INDEXCRITICAL
c
+findbugs:UCF_USELESS_CONTROL_FLOW_NEXT_LINE4
findbugs"UCF_USELESS_CONTROL_FLOW_NEXT_LINEINFO
S
#findbugs:CAA_COVARIANT_ARRAY_RETURN,
findbugsCAA_COVARIANT_ARRAY_RETURNINFO
T
#findbugs:PT_ABSOLUTE_PATH_TRAVERSAL-
findbugsPT_ABSOLUTE_PATH_TRAVERSALMAJOR
o
1findbugs:RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE:
findbugs(RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUEINFO
E
findbugs:REC_CATCH_EXCEPTION%
findbugsREC_CATCH_EXCEPTIONINFO
^
(findbugs:IIL_ELEMENTS_GET_LENGTH_IN_LOOP2
findbugsIIL_ELEMENTS_GET_LENGTH_IN_LOOPMAJOR
p
1findbugs:JCIP_FIELD_ISNT_FINAL_IN_IMMUTABLE_CLASS;
findbugs(JCIP_FIELD_ISNT_FINAL_IN_IMMUTABLE_CLASSMAJOR
r
2findbugs:TQ_ALWAYS_VALUE_USED_WHERE_NEVER_REQUIRED<
findbugs)TQ_ALWAYS_VALUE_USED_WHERE_NEVER_REQUIREDMAJOR
\
'findbugs:DM_BOXED_PRIMITIVE_FOR_PARSING1
findbugsDM_BOXED_PRIMITIVE_FOR_PARSINGMAJOR
n
0findbugs:ICAST_INT_CAST_TO_DOUBLE_PASSED_TO_CEIL:
findbugs'ICAST_INT_CAST_TO_DOUBLE_PASSED_TO_CEILMAJOR
J
findbugs:IS2_INCONSISTENT_SYNC(
findbugsIS2_INCONSISTENT_SYNCMAJOR
J
findbugs:SE_NO_SERIALVERSIONID(
findbugsSE_NO_SERIALVERSIONIDMAJOR
0
findbugs:FI_EMPTY
findbugsFI_EMPTYMAJOR
G
findbugs:MS_MUTABLE_HASHTABLE&
findbugsMS_MUTABLE_HASHTABLEINFO
`
)findbugs:STI_INTERRUPTED_ON_UNKNOWNTHREAD3
findbugs STI_INTERRUPTED_ON_UNKNOWNTHREADMAJOR
v
4findbugs:NM_FUTURE_KEYWORD_USED_AS_MEMBER_IDENTIFIER>
findbugs+NM_FUTURE_KEYWORD_USED_AS_MEMBER_IDENTIFIERMAJOR
R
"findbugs:SA_LOCAL_SELF_COMPUTATION,
findbugsSA_LOCAL_SELF_COMPUTATIONMAJOR
R
"findbugs:SE_METHOD_MUST_BE_PRIVATE,
findbugsSE_METHOD_MUST_BE_PRIVATEMAJOR
<
findbugs:WA_NOT_IN_LOOP!
findbugsWA_NOT_IN_LOOPMAJOR
f
,findbugs:DMI_VACUOUS_CALL_TO_EASYMOCK_METHOD6
findbugs#DMI_VACUOUS_CALL_TO_EASYMOCK_METHODMAJOR
h
-findbugs:IP_PARAMETER_IS_DEAD_BUT_OVERWRITTEN7
findbugs$IP_PARAMETER_IS_DEAD_BUT_OVERWRITTENMAJOR
€
9findbugs:SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH_TO_THROWC
findbugs0SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH_TO_THROWMAJOR
L
findbugs:UG_SYNC_SET_UNSYNC_GET)
findbugsUG_SYNC_SET_UNSYNC_GETMAJOR
\
'findbugs:FI_FINALIZER_ONLY_NULLS_FIELDS1
findbugsFI_FINALIZER_ONLY_NULLS_FIELDSMAJOR
|
7findbugs:SE_NO_SUITABLE_CONSTRUCTOR_FOR_EXTERNALIZATIONA
findbugs.SE_NO_SUITABLE_CONSTRUCTOR_FOR_EXTERNALIZATIONMAJOR
M
 findbugs:CI_CONFUSED_INHERITANCE)
findbugsCI_CONFUSED_INHERITANCEINFO
B
findbugs:NM_LCASE_TOSTRING$
findbugsNM_LCASE_TOSTRINGMAJOR
Z
&findbugs:NM_VERY_CONFUSING_INTENTIONAL0
findbugsNM_VERY_CONFUSING_INTENTIONALMAJOR
R
"findbugs:DMI_RANDOM_USED_ONLY_ONCE,
findbugsDMI_RANDOM_USED_ONLY_ONCEMAJOR
q
2findbugs:DMI_THREAD_PASSED_WHERE_RUNNABLE_EXPECTED;
findbugs)DMI_THREAD_PASSED_WHERE_RUNNABLE_EXPECTEDINFO
F
findbugs:NP_NULL_PARAM_DEREF&
findbugsNP_NULL_PARAM_DEREFMAJOR
\
'findbugs:RE_POSSIBLE_UNINTENDED_PATTERN1
findbugsRE_POSSIBLE_UNINTENDED_PATTERNMAJOR
L
findbugs:BIT_IOR_OF_SIGNED_BYTE)
findbugsBIT_IOR_OF_SIGNED_BYTEMAJOR
9
findbugs:EI_EXPOSE_REP
findbugsEI_EXPOSE_REPINFO
>
findbugs:EQ_ALWAYS_FALSE"
findbugsEQ_ALWAYS_FALSEMAJOR
<
findbugs:DC_DOUBLECHECK!
findbugsDC_DOUBLECHECKMAJOR
X
%findbugs:DM_MONITOR_WAIT_ON_CONDITION/
findbugsDM_MONITOR_WAIT_ON_CONDITIONMAJOR
:
findbugs:DMI_BAD_MONTH 
findbugsDMI_BAD_MONTHMAJOR
G
findbugs:IM_BAD_CHECK_FOR_ODD&
findbugsIM_BAD_CHECK_FOR_ODDINFO
c
+findbugs:DLS_DEAD_LOCAL_STORE_SHADOWS_FIELD4
findbugs"DLS_DEAD_LOCAL_STORE_SHADOWS_FIELDINFO
l
/findbugs:DMI_ENTRY_SETS_MAY_REUSE_ENTRY_OBJECTS9
findbugs&DMI_ENTRY_SETS_MAY_REUSE_ENTRY_OBJECTSMAJOR
T
#findbugs:IL_INFINITE_RECURSIVE_LOOP-
findbugsIL_INFINITE_RECURSIVE_LOOPMAJOR
_
)findbugs:NP_DEREFERENCE_OF_READLINE_VALUE2
findbugs NP_DEREFERENCE_OF_READLINE_VALUEINFO
@
findbugs:SC_START_IN_CTOR#
findbugsSC_START_IN_CTORMAJOR
L
findbugs:WMI_WRONG_MAP_ITERATOR)
findbugsWMI_WRONG_MAP_ITERATORMAJOR
b
*findbugs:CAA_COVARIANT_ARRAY_ELEMENT_STORE4
findbugs!CAA_COVARIANT_ARRAY_ELEMENT_STOREMAJOR
G
findbugs:DLS_DEAD_LOCAL_STORE&
findbugsDLS_DEAD_LOCAL_STOREINFO
Y
&findbugs:RV_CHECK_FOR_POSITIVE_INDEXOF/
findbugsRV_CHECK_FOR_POSITIVE_INDEXOFINFO
\
'findbugs:VO_VOLATILE_REFERENCE_TO_ARRAY1
findbugsVO_VOLATILE_REFERENCE_TO_ARRAYMAJOR
^
(findbugs:AM_CREATES_EMPTY_JAR_FILE_ENTRY2
findbugsAM_CREATES_EMPTY_JAR_FILE_ENTRYMAJOR
e
,findbugs:MS_SHOULD_BE_REFACTORED_TO_BE_FINAL5
findbugs#MS_SHOULD_BE_REFACTORED_TO_BE_FINALINFO
<
findbugs:UW_UNCOND_WAIT!
findbugsUW_UNCOND_WAITMAJOR
c
+findbugs:BC_BAD_CAST_TO_CONCRETE_COLLECTION4
findbugs"BC_BAD_CAST_TO_CONCRETE_COLLECTIONINFO
J
findbugs:MWN_MISMATCHED_NOTIFY(
findbugsMWN_MISMATCHED_NOTIFYMAJOR
p
1findbugs:SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE;
findbugs(SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTEMAJOR
P
!findbugs:SA_LOCAL_SELF_COMPARISON+
findbugsSA_LOCAL_SELF_COMPARISONMAJOR
R
"findbugs:SE_READ_RESOLVE_IS_STATIC,
findbugsSE_READ_RESOLVE_IS_STATICMAJOR
Z
&findbugs:VA_FORMAT_STRING_USES_NEWLINE0
findbugsVA_FORMAT_STRING_USES_NEWLINEMAJOR
J
findbugs:VO_VOLATILE_INCREMENT(
findbugsVO_VOLATILE_INCREMENTMAJOR
r
2findbugs:JML_JSR166_CALLING_WAIT_RATHER_THAN_AWAIT<
findbugs)JML_JSR166_CALLING_WAIT_RATHER_THAN_AWAITMAJOR
h
-findbugs:NM_FUTURE_KEYWORD_USED_AS_IDENTIFIER7
findbugs$NM_FUTURE_KEYWORD_USED_AS_IDENTIFIERMAJOR
G
findbugs:RANGE_ARRAY_LENGTH(
findbugsRANGE_ARRAY_LENGTHCRITICAL
S
!findbugs:BC_IMPOSSIBLE_INSTANCEOF.
findbugsBC_IMPOSSIBLE_INSTANCEOFCRITICAL
v
4findbugs:DMI_ANNOTATION_IS_NOT_VISIBLE_TO_REFLECTION>
findbugs+DMI_ANNOTATION_IS_NOT_VISIBLE_TO_REFLECTIONMAJOR
\
'findbugs:DMI_INVOKING_HASHCODE_ON_ARRAY1
findbugsDMI_INVOKING_HASHCODE_ON_ARRAYMAJOR
X
%findbugs:IL_CONTAINER_ADDED_TO_ITSELF/
findbugsIL_CONTAINER_ADDED_TO_ITSELFMAJOR
v
4findbugs:BX_UNBOXED_AND_COERCED_FOR_TERNARY_OPERATOR>
findbugs+BX_UNBOXED_AND_COERCED_FOR_TERNARY_OPERATORMAJOR
m
0findbugs:NP_METHOD_PARAMETER_RELAXING_ANNOTATION9
findbugs'NP_METHOD_PARAMETER_RELAXING_ANNOTATIONINFO
X
%findbugs:NP_SYNC_AND_NULL_CHECK_FIELD/
findbugsNP_SYNC_AND_NULL_CHECK_FIELDMAJOR
<
findbugs:DM_STRING_CTOR!
findbugsDM_STRING_CTORMAJOR
E
findbugs:IC_INIT_CIRCULARITY%
findbugsIC_INIT_CIRCULARITYINFO
J
findbugs:IJU_TEARDOWN_NO_SUPER(
findbugsIJU_TEARDOWN_NO_SUPERMAJOR
L
findbugs:NP_BOOLEAN_RETURN_NULL)
findbugsNP_BOOLEAN_RETURN_NULLMAJOR
K
findbugs:CD_CIRCULAR_DEPENDENCY(
findbugsCD_CIRCULAR_DEPENDENCYINFO
U
$findbugs:DB_DUPLICATE_SWITCH_CLAUSES-
findbugsDB_DUPLICATE_SWITCH_CLAUSESINFO
k
/findbugs:NP_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD8
findbugs&NP_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELDINFO
.
findbugs:DMI_DOH
findbugsDMI_DOHMAJOR
J
findbugs:HE_HASHCODE_NO_EQUALS(
findbugsHE_HASHCODE_NO_EQUALSMAJOR
„
;findbugs:J2EE_STORE_OF_NON_SERIALIZABLE_OBJECT_INTO_SESSIONE
findbugs2J2EE_STORE_OF_NON_SERIALIZABLE_OBJECT_INTO_SESSIONMAJOR
D
findbugs:UL_UNRELEASED_LOCK%
findbugsUL_UNRELEASED_LOCKMAJOR
D
findbugs:DM_INVALID_MIN_MAX%
findbugsDM_INVALID_MIN_MAXMAJOR
V
$findbugs:DMI_BLOCKING_METHODS_ON_URL.
findbugsDMI_BLOCKING_METHODS_ON_URLMAJOR
f
,findbugs:QBA_QUESTIONABLE_BOOLEAN_ASSIGNMENT6
findbugs#QBA_QUESTIONABLE_BOOLEAN_ASSIGNMENTMAJOR
j
.findbugs:ES_COMPARING_PARAMETER_STRING_WITH_EQ8
findbugs%ES_COMPARING_PARAMETER_STRING_WITH_EQMAJOR
i
.findbugs:IM_AVERAGE_COMPUTATION_COULD_OVERFLOW7
findbugs%IM_AVERAGE_COMPUTATION_COULD_OVERFLOWINFO
h
-findbugs:RV_RETURN_VALUE_IGNORED_BAD_PRACTICE7
findbugs$RV_RETURN_VALUE_IGNORED_BAD_PRACTICEMAJOR
^
(findbugs:SE_TRANSIENT_FIELD_NOT_RESTORED2
findbugsSE_TRANSIENT_FIELD_NOT_RESTOREDMAJOR
~
8findbugs:AT_OPERATION_SEQUENCE_ON_CONCURRENT_ABSTRACTIONB
findbugs/AT_OPERATION_SEQUENCE_ON_CONCURRENT_ABSTRACTIONMAJOR
T
#findbugs:ODR_OPEN_DATABASE_RESOURCE-
findbugsODR_OPEN_DATABASE_RESOURCEMAJOR
n
0findbugs:XSS_REQUEST_PARAMETER_TO_SERVLET_WRITER:
findbugs'XSS_REQUEST_PARAMETER_TO_SERVLET_WRITERMAJOR
>
findbugs:DM_BOOLEAN_CTOR"
findbugsDM_BOOLEAN_CTORMAJOR
z
6findbugs:EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS@
findbugs-EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THISMAJOR
<
findbugs:NP_ALWAYS_NULL!
findbugsNP_ALWAYS_NULLMAJOR
X
%findbugs:ES_COMPARING_STRINGS_WITH_EQ/
findbugsES_COMPARING_STRINGS_WITH_EQMAJOR
X
%findbugs:ISC_INSTANTIATE_STATIC_CLASS/
findbugsISC_INSTANTIATE_STATIC_CLASSMAJOR
H
findbugs:MF_CLASS_MASKS_FIELD'
findbugsMF_CLASS_MASKS_FIELDMAJOR
z
6findbugs:DMI_COLLECTIONS_SHOULD_NOT_CONTAIN_THEMSELVES@
findbugs-DMI_COLLECTIONS_SHOULD_NOT_CONTAIN_THEMSELVESMAJOR
@
findbugs:IL_INFINITE_LOOP#
findbugsIL_INFINITE_LOOPMAJOR
v
4findbugs:STCAL_INVOKE_ON_STATIC_DATE_FORMAT_INSTANCE>
findbugs+STCAL_INVOKE_ON_STATIC_DATE_FORMAT_INSTANCEMAJOR
M
 findbugs:UC_USELESS_OBJECT_STACK)
findbugsUC_USELESS_OBJECT_STACKINFO
M
 findbugs:RI_REDUNDANT_INTERFACES)
findbugsRI_REDUNDANT_INTERFACESINFO
^
(findbugs:RV_ABSOLUTE_VALUE_OF_RANDOM_INT2
findbugsRV_ABSOLUTE_VALUE_OF_RANDOM_INTMAJOR
u
4findbugs:SE_TRANSIENT_FIELD_OF_NONSERIALIZABLE_CLASS=
findbugs+SE_TRANSIENT_FIELD_OF_NONSERIALIZABLE_CLASSINFO
P
!findbugs:IIO_INEFFICIENT_INDEX_OF+
findbugsIIO_INEFFICIENT_INDEX_OFMAJOR
<
findbugs:SE_INNER_CLASS!
findbugsSE_INNER_CLASSMAJOR
F
findbugs:WS_WRITEOBJECT_SYNC&
findbugsWS_WRITEOBJECT_SYNCMAJOR
J
findbugs:DMI_EMPTY_DB_PASSWORD(
findbugsDMI_EMPTY_DB_PASSWORDMAJOR
c
+findbugs:MTIA_SUSPECT_STRUTS_INSTANCE_FIELD4
findbugs"MTIA_SUSPECT_STRUTS_INSTANCE_FIELDINFO
d
+findbugs:SE_READ_RESOLVE_MUST_RETURN_OBJECT5
findbugs"SE_READ_RESOLVE_MUST_RETURN_OBJECTMAJOR
R
"findbugs:BSHIFT_WRONG_ADD_PRIORITY,
findbugsBSHIFT_WRONG_ADD_PRIORITYMAJOR
B
findbugs:EQ_SELF_NO_OBJECT$
findbugsEQ_SELF_NO_OBJECTMAJOR

Afindbugs:SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRINGK
findbugs8SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRINGMAJOR
A
findbugs:UC_USELESS_OBJECT#
findbugsUC_USELESS_OBJECTINFO
:
findbugs:DE_MIGHT_DROP 
findbugsDE_MIGHT_DROPMAJOR
@
findbugs:ESync_EMPTY_SYNC#
findbugsESync_EMPTY_SYNCMAJOR
e
,findbugs:MTIA_SUSPECT_SERVLET_INSTANCE_FIELD5
findbugs#MTIA_SUSPECT_SERVLET_INSTANCE_FIELDINFO
B
findbugs:DM_FP_NUMBER_CTOR$
findbugsDM_FP_NUMBER_CTORMAJOR
L
findbugs:ICAST_BAD_SHIFT_AMOUNT)
findbugsICAST_BAD_SHIFT_AMOUNTMAJOR
F
findbugs:SS_SHOULD_BE_STATIC&
findbugsSS_SHOULD_BE_STATICMAJOR
I
findbugs:DMI_USELESS_SUBSTRING'
findbugsDMI_USELESS_SUBSTRINGINFO
?
findbugs:MS_MUTABLE_ARRAY"
findbugsMS_MUTABLE_ARRAYINFO
I
findbugs:MS_MUTABLE_COLLECTION'
findbugsMS_MUTABLE_COLLECTIONINFO
D
findbugs:IT_NO_SUCH_ELEMENT%
findbugsIT_NO_SUCH_ELEMENTMAJOR
B
findbugs:NM_VERY_CONFUSING$
findbugsNM_VERY_CONFUSINGMAJOR
U
$findbugs:USM_USELESS_ABSTRACT_METHOD-
findbugsUSM_USELESS_ABSTRACT_METHODINFO
P
!findbugs:VA_FORMAT_STRING_ILLEGAL+
findbugsVA_FORMAT_STRING_ILLEGALMAJOR
.
findbugs:BIT_IOR
findbugsBIT_IORMAJOR
F
findbugs:EQ_OTHER_USE_OBJECT&
findbugsEQ_OTHER_USE_OBJECTMAJOR
Z
&findbugs:RV_ABSOLUTE_VALUE_OF_HASHCODE0
findbugsRV_ABSOLUTE_VALUE_OF_HASHCODEMAJOR
R
"findbugs:BRSA_BAD_RESULTSET_ACCESS,
findbugsBRSA_BAD_RESULTSET_ACCESSMAJOR
^
(findbugs:DLS_DEAD_STORE_OF_CLASS_LITERAL2
findbugsDLS_DEAD_STORE_OF_CLASS_LITERALMAJOR
S
#findbugs:SA_LOCAL_DOUBLE_ASSIGNMENT,
findbugsSA_LOCAL_DOUBLE_ASSIGNMENTINFO
r
2findbugs:TQ_NEVER_VALUE_USED_WHERE_ALWAYS_REQUIRED<
findbugs)TQ_NEVER_VALUE_USED_WHERE_ALWAYS_REQUIREDMAJOR
^
(findbugs:RV_NEGATING_RESULT_OF_COMPARETO2
findbugsRV_NEGATING_RESULT_OF_COMPARETOMAJOR
p
1findbugs:TQ_MAYBE_SOURCE_VALUE_REACHES_NEVER_SINK;
findbugs(TQ_MAYBE_SOURCE_VALUE_REACHES_NEVER_SINKMAJOR
n
0findbugs:VA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSED:
findbugs'VA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSEDMAJOR
`
)findbugs:FE_TEST_IF_EQUAL_TO_NOT_A_NUMBER3
findbugs FE_TEST_IF_EQUAL_TO_NOT_A_NUMBERMAJOR
m
0findbugs:ICAST_QUESTIONABLE_UNSIGNED_RIGHT_SHIFT9
findbugs'ICAST_QUESTIONABLE_UNSIGNED_RIGHT_SHIFTINFO
ˆ
=findbugs:TQ_UNKNOWN_VALUE_USED_WHERE_ALWAYS_STRICTLY_REQUIREDG
findbugs4TQ_UNKNOWN_VALUE_USED_WHERE_ALWAYS_STRICTLY_REQUIREDMAJOR
m
0findbugs:UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD9
findbugs'UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELDINFO
e
*findbugs:BC_IMPOSSIBLE_DOWNCAST_OF_TOARRAY7
findbugs!BC_IMPOSSIBLE_DOWNCAST_OF_TOARRAYCRITICAL
L
findbugs:HE_EQUALS_USE_HASHCODE)
findbugsHE_EQUALS_USE_HASHCODEMAJOR
_
)findbugs:RV_RETURN_VALUE_IGNORED_INFERRED2
findbugs RV_RETURN_VALUE_IGNORED_INFERREDINFO
H
findbugs:ME_ENUM_FIELD_SETTER'
findbugsME_ENUM_FIELD_SETTERMAJOR
8
findbugs:RV_01_TO_INT
findbugsRV_01_TO_INTMAJOR
T
#findbugs:SIO_SUPERFLUOUS_INSTANCEOF-
findbugsSIO_SUPERFLUOUS_INSTANCEOFMAJOR
c
+findbugs:BC_BAD_CAST_TO_ABSTRACT_COLLECTION4
findbugs"BC_BAD_CAST_TO_ABSTRACT_COLLECTIONINFO
n
0findbugs:ICAST_INT_CAST_TO_FLOAT_PASSED_TO_ROUND:
findbugs'ICAST_INT_CAST_TO_FLOAT_PASSED_TO_ROUNDMAJOR
P
!findbugs:ITA_INEFFICIENT_TO_ARRAY+
findbugsITA_INEFFICIENT_TO_ARRAYMAJOR
h
-findbugs:RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSION7
findbugs$RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSIONMAJOR
F
findbugs:MWN_MISMATCHED_WAIT&
findbugsMWN_MISMATCHED_WAITMAJOR
p
1findbugs:STCAL_STATIC_SIMPLE_DATE_FORMAT_INSTANCE;
findbugs(STCAL_STATIC_SIMPLE_DATE_FORMAT_INSTANCEMAJOR
‚
:findbugs:VA_FORMAT_STRING_EXPECTED_MESSAGE_FORMAT_SUPPLIEDD
findbugs1VA_FORMAT_STRING_EXPECTED_MESSAGE_FORMAT_SUPPLIEDMAJOR
U
$findbugs:NP_LOAD_OF_KNOWN_NULL_VALUE-
findbugsNP_LOAD_OF_KNOWN_NULL_VALUEINFO
T
#findbugs:NP_NONNULL_PARAM_VIOLATION-
findbugsNP_NONNULL_PARAM_VIOLATIONMAJOR
L
findbugs:BIT_ADD_OF_SIGNED_BYTE)
findbugsBIT_ADD_OF_SIGNED_BYTEMAJOR
d
+findbugs:DLS_DEAD_LOCAL_INCREMENT_IN_RETURN5
findbugs"DLS_DEAD_LOCAL_INCREMENT_IN_RETURNMAJOR
Y
&findbugs:FI_PUBLIC_SHOULD_BE_PROTECTED/
findbugsFI_PUBLIC_SHOULD_BE_PROTECTEDINFO
P
!findbugs:SE_BAD_FIELD_INNER_CLASS+
findbugsSE_BAD_FIELD_INNER_CLASSMAJOR
j
.findbugs:DL_SYNCHRONIZATION_ON_SHARED_CONSTANT8
findbugs%DL_SYNCHRONIZATION_ON_SHARED_CONSTANTMAJOR
J
findbugs:FB_UNEXPECTED_WARNING(
findbugsFB_UNEXPECTED_WARNINGMAJOR
D
findbugs:GC_UNRELATED_TYPES%
findbugsGC_UNRELATED_TYPESMAJOR
F
findbugs:LI_LAZY_INIT_STATIC&
findbugsLI_LAZY_INIT_STATICMAJOR
C
findbugs:MS_SHOULD_BE_FINAL$
findbugsMS_SHOULD_BE_FINALINFO
\
'findbugs:RC_REF_COMPARISON_BAD_PRACTICE1
findbugsRC_REF_COMPARISON_BAD_PRACTICEMAJOR
Q
"findbugs:UC_USELESS_CONDITION_TYPE+
findbugsUC_USELESS_CONDITION_TYPEINFO
g
-findbugs:NP_METHOD_RETURN_RELAXING_ANNOTATION6
findbugs$NP_METHOD_RETURN_RELAXING_ANNOTATIONINFO
C
findbugs:RV_REM_OF_HASHCODE$
findbugsRV_REM_OF_HASHCODEINFO
o
1findbugs:UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR:
findbugs(UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTORINFO
^
(findbugs:CO_COMPARETO_INCORRECT_FLOATING2
findbugsCO_COMPARETO_INCORRECT_FLOATINGMAJOR
ƒ
;findbugs:RCN_REDUNDANT_COMPARISON_OF_NULL_AND_NONNULL_VALUED
findbugs2RCN_REDUNDANT_COMPARISON_OF_NULL_AND_NONNULL_VALUEINFO
T
#findbugs:SE_NO_SUITABLE_CONSTRUCTOR-
findbugsSE_NO_SUITABLE_CONSTRUCTORMAJOR
G
findbugs:UC_USELESS_CONDITION&
findbugsUC_USELESS_CONDITIONINFO
W
%findbugs:DLS_DEAD_LOCAL_STORE_OF_NULL.
findbugsDLS_DEAD_LOCAL_STORE_OF_NULLINFO
T
#findbugs:HE_USE_OF_UNHASHABLE_CLASS-
findbugsHE_USE_OF_UNHASHABLE_CLASSMAJOR
R
"findbugs:SA_FIELD_SELF_COMPUTATION,
findbugsSA_FIELD_SELF_COMPUTATIONMAJOR
Z
&findbugs:VA_FORMAT_STRING_BAD_ARGUMENT0
findbugsVA_FORMAT_STRING_BAD_ARGUMENTMAJOR
Z
&findbugs:DMI_CALLING_NEXT_FROM_HASNEXT0
findbugsDMI_CALLING_NEXT_FROM_HASNEXTMAJOR
T
#findbugs:NM_CLASS_NAMING_CONVENTION-
findbugsNM_CLASS_NAMING_CONVENTIONMAJOR
T
#findbugs:NM_FIELD_NAMING_CONVENTION-
findbugsNM_FIELD_NAMING_CONVENTIONMAJOR
f
,findbugs:SBSC_USE_STRINGBUFFER_CONCATENATION6
findbugs#SBSC_USE_STRINGBUFFER_CONCATENATIONMAJOR
I
findbugs:BC_VACUOUS_INSTANCEOF'
findbugsBC_VACUOUS_INSTANCEOFINFO
8
findbugs:IJU_NO_TESTS
findbugsIJU_NO_TESTSMAJOR
D
findbugs:IJU_SETUP_NO_SUPER%
findbugsIJU_SETUP_NO_SUPERMAJOR
r
2findbugs:INT_BAD_COMPARISON_WITH_NONNEGATIVE_VALUE<
findbugs)INT_BAD_COMPARISON_WITH_NONNEGATIVE_VALUEMAJOR
@
findbugs:SP_SPIN_ON_FIELD#
findbugsSP_SPIN_ON_FIELDMAJOR
‡
=findbugs:TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_ALWAYS_SINKF
findbugs4TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_ALWAYS_SINKINFO
N
 findbugs:NP_OPTIONAL_RETURN_NULL*
findbugsNP_OPTIONAL_RETURN_NULLMAJOR
b
*findbugs:VA_FORMAT_STRING_MISSING_ARGUMENT4
findbugs!VA_FORMAT_STRING_MISSING_ARGUMENTMAJOR
^
(findbugs:BX_UNBOXING_IMMEDIATELY_REBOXED2
findbugsBX_UNBOXING_IMMEDIATELY_REBOXEDMAJOR
R
"findbugs:DM_NEXTINT_VIA_NEXTDOUBLE,
findbugsDM_NEXTINT_VIA_NEXTDOUBLEMAJOR
\
'findbugs:NP_NULL_ON_SOME_PATH_EXCEPTION1
findbugsNP_NULL_ON_SOME_PATH_EXCEPTIONMAJOR
P
!findbugs:SA_FIELD_SELF_ASSIGNMENT+
findbugsSA_FIELD_SELF_ASSIGNMENTMAJOR
e
,findbugs:ICAST_INTEGER_MULTIPLY_CAST_TO_LONG5
findbugs#ICAST_INTEGER_MULTIPLY_CAST_TO_LONGINFO
V
$findbugs:NM_METHOD_NAMING_CONVENTION.
findbugsNM_METHOD_NAMING_CONVENTIONMAJOR
T
#findbugs:SIC_INNER_SHOULD_BE_STATIC-
findbugsSIC_INNER_SHOULD_BE_STATICMAJOR
Q
"findbugs:CAA_COVARIANT_ARRAY_LOCAL+
findbugsCAA_COVARIANT_ARRAY_LOCALINFO
L
findbugs:CN_IDIOM_NO_SUPER_CALL)
findbugsCN_IDIOM_NO_SUPER_CALLMAJOR
B
findbugs:CO_SELF_NO_OBJECT$
findbugsCO_SELF_NO_OBJECTMAJOR
<
findbugs:OS_OPEN_STREAM!
findbugsOS_OPEN_STREAMMAJOR
P
!findbugs:CNT_ROUGH_CONSTANT_VALUE+
findbugsCNT_ROUGH_CONSTANT_VALUEMAJOR
=
findbugs:DM_CONVERT_CASE!
findbugsDM_CONVERT_CASEINFO
Z
&findbugs:VA_FORMAT_STRING_ARG_MISMATCH0
findbugsVA_FORMAT_STRING_ARG_MISMATCHMAJOR
L
findbugs:NM_CLASS_NOT_EXCEPTION)
findbugsNM_CLASS_NOT_EXCEPTIONMAJOR
p
1findbugs:PZ_DONT_REUSE_ENTRY_OBJECTS_IN_ITERATORS;
findbugs(PZ_DONT_REUSE_ENTRY_OBJECTS_IN_ITERATORSMAJOR
n
0findbugs:DMI_USING_REMOVEALL_TO_CLEAR_COLLECTION:
findbugs'DMI_USING_REMOVEALL_TO_CLEAR_COLLECTIONMAJOR
H
findbugs:IMSE_DONT_CATCH_IMSE'
findbugsIMSE_DONT_CATCH_IMSEMAJOR
l
/findbugs:JLM_JSR166_UTILCONCURRENT_MONITORENTER9
findbugs&JLM_JSR166_UTILCONCURRENT_MONITORENTERMAJOR
V
$findbugs:NP_STORE_INTO_NONNULL_FIELD.
findbugsNP_STORE_INTO_NONNULL_FIELDMAJOR
Z
&findbugs:DL_SYNCHRONIZATION_ON_BOOLEAN0
findbugsDL_SYNCHRONIZATION_ON_BOOLEANMAJOR
Q
"findbugs:EQ_DOESNT_OVERRIDE_EQUALS+
findbugsEQ_DOESNT_OVERRIDE_EQUALSINFO
H
findbugs:IS_INCONSISTENT_SYNC'
findbugsIS_INCONSISTENT_SYNCMAJOR
‚
:findbugs:IC_SUPERCLASS_USES_SUBCLASS_DURING_INITIALIZATIOND
findbugs1IC_SUPERCLASS_USES_SUBCLASS_DURING_INITIALIZATIONMAJOR
K
findbugs:INT_VACUOUS_COMPARISON(
findbugsINT_VACUOUS_COMPARISONINFO
l
/findbugs:RV_RETURN_VALUE_OF_PUTIFABSENT_IGNORED9
findbugs&RV_RETURN_VALUE_OF_PUTIFABSENT_IGNOREDMAJOR
F
findbugs:UM_UNNECESSARY_MATH&
findbugsUM_UNNECESSARY_MATHMAJOR
x
5findbugs:BC_EQUALS_METHOD_SHOULD_WORK_FOR_ALL_OBJECTS?
findbugs,BC_EQUALS_METHOD_SHOULD_WORK_FOR_ALL_OBJECTSMAJOR
0
findbugs:CN_IDIOM
findbugsCN_IDIOMMAJOR
m
0findbugs:NP_METHOD_PARAMETER_TIGHTENS_ANNOTATION9
findbugs'NP_METHOD_PARAMETER_TIGHTENS_ANNOTATIONINFO
@
findbugs:FI_NULLIFY_SUPER#
findbugsFI_NULLIFY_SUPERMAJOR
F
findbugs:NP_GUARANTEED_DEREF&
findbugsNP_GUARANTEED_DEREFMAJOR
g
-findbugs:NP_IMMEDIATE_DEREFERENCE_OF_READLINE6
findbugs$NP_IMMEDIATE_DEREFERENCE_OF_READLINEINFO
i
.findbugs:SE_PRIVATE_READ_RESOLVE_NOT_INHERITED7
findbugs%SE_PRIVATE_READ_RESOLVE_NOT_INHERITEDINFO
;
findbugs:EI_EXPOSE_REP2 
findbugsEI_EXPOSE_REP2INFO
P
!findbugs:SA_FIELD_SELF_COMPARISON+
findbugsSA_FIELD_SELF_COMPARISONMAJOR
H
findbugs:WA_AWAIT_NOT_IN_LOOP'
findbugsWA_AWAIT_NOT_IN_LOOPMAJOR
d
+findbugs:EQ_OVERRIDING_EQUALS_NOT_SYMMETRIC5
findbugs"EQ_OVERRIDING_EQUALS_NOT_SYMMETRICMAJOR
3
findbugs:EQ_UNUSUAL
findbugs
EQ_UNUSUALINFO
N
 findbugs:RV_EXCEPTION_NOT_THROWN*
findbugsRV_EXCEPTION_NOT_THROWNMAJOR
X
%findbugs:SE_NONSTATIC_SERIALVERSIONID/
findbugsSE_NONSTATIC_SERIALVERSIONIDMAJOR
‚
:findbugs:HE_SIGNATURE_DECLARES_HASHING_OF_UNHASHABLE_CLASSD
findbugs1HE_SIGNATURE_DECLARES_HASHING_OF_UNHASHABLE_CLASSMAJOR
b
*findbugs:INT_BAD_COMPARISON_WITH_INT_VALUE4
findbugs!INT_BAD_COMPARISON_WITH_INT_VALUEMAJOR
j
.findbugs:VA_FORMAT_STRING_NO_PREVIOUS_ARGUMENT8
findbugs%VA_FORMAT_STRING_NO_PREVIOUS_ARGUMENTMAJOR
\
'findbugs:DM_BOXED_PRIMITIVE_FOR_COMPARE1
findbugsDM_BOXED_PRIMITIVE_FOR_COMPAREMAJOR
9
findbugs:MS_PKGPROTECT
findbugsMS_PKGPROTECTINFO
<
findbugs:UR_UNINIT_READ!
findbugsUR_UNINIT_READMAJOR
R
"findbugs:VR_UNRESOLVABLE_REFERENCE,
findbugsVR_UNRESOLVABLE_REFERENCEMAJOR
N
 findbugs:NO_NOTIFY_NOT_NOTIFYALL*
findbugsNO_NOTIFY_NOT_NOTIFYALLMAJOR
z
6findbugs:ML_SYNC_ON_FIELD_TO_GUARD_CHANGING_THAT_FIELD@
findbugs-ML_SYNC_ON_FIELD_TO_GUARD_CHANGING_THAT_FIELDMAJOR
p
1fb-contrib:BRPI_BACKPORT_REUSE_PUBLIC_IDENTIFIERS;

fb-contrib&BRPI_BACKPORT_REUSE_PUBLIC_IDENTIFIERSMAJOR
N
 fb-contrib:S508C_APPENDED_STRING*

fb-contribS508C_APPENDED_STRINGMAJOR
_
)fb-contrib:IMC_IMMATURE_CLASS_NO_TOSTRING2

fb-contribIMC_IMMATURE_CLASS_NO_TOSTRINGINFO
F
fb-contrib:MDM_LOCK_ISLOCKED&

fb-contribMDM_LOCK_ISLOCKEDMAJOR
T
#fb-contrib:NFF_NON_FUNCTIONAL_FIELD-

fb-contribNFF_NON_FUNCTIONAL_FIELDMAJOR
I
fb-contrib:SPP_USE_CONTAINSKEY'

fb-contribSPP_USE_CONTAINSKEYINFO
v
4fb-contrib:SWCO_SUSPICIOUS_WAIT_ON_CONCURRENT_OBJECT>

fb-contrib)SWCO_SUSPICIOUS_WAIT_ON_CONCURRENT_OBJECTMAJOR
[
'fb-contrib:WEM_WEAK_EXCEPTION_MESSAGING0

fb-contribWEM_WEAK_EXCEPTION_MESSAGINGINFO
]
(fb-contrib:ITC_INHERITANCE_TYPE_CHECKING1

fb-contribITC_INHERITANCE_TYPE_CHECKINGINFO
N
 fb-contrib:MDM_THREAD_PRIORITIES*

fb-contribMDM_THREAD_PRIORITIESMAJOR
A
fb-contrib:SPP_USE_ISEMPTY#

fb-contribSPP_USE_ISEMPTYINFO
\
'fb-contrib:MDM_INETADDRESS_GETLOCALHOST1

fb-contribMDM_INETADDRESS_GETLOCALHOSTMAJOR
^
(fb-contrib:S508C_NON_TRANSLATABLE_STRING2

fb-contribS508C_NON_TRANSLATABLE_STRINGMAJOR
\
'fb-contrib:SPP_USE_STRINGBUILDER_LENGTH1

fb-contribSPP_USE_STRINGBUILDER_LENGTHMAJOR
b
*fb-contrib:LEST_LOST_EXCEPTION_STACK_TRACE4

fb-contribLEST_LOST_EXCEPTION_STACK_TRACEMAJOR
O
!fb-contrib:STB_STACKED_TRY_BLOCKS*

fb-contribSTB_STACKED_TRY_BLOCKSINFO
T
#fb-contrib:UEC_USE_ENUM_COLLECTIONS-

fb-contribUEC_USE_ENUM_COLLECTIONSMAJOR
‚
:fb-contrib:JPAI_UNNECESSARY_TRANSACTION_EXCEPTION_HANDLINGD

fb-contrib/JPAI_UNNECESSARY_TRANSACTION_EXCEPTION_HANDLINGMAJOR
B
fb-contrib:MDM_RANDOM_SEED$

fb-contribMDM_RANDOM_SEEDMAJOR
T
#fb-contrib:NSE_NON_SYMMETRIC_EQUALS-

fb-contribNSE_NON_SYMMETRIC_EQUALSMAJOR
d
+fb-contrib:ISB_INEFFICIENT_STRING_BUFFERING5

fb-contrib ISB_INEFFICIENT_STRING_BUFFERINGMAJOR
_
)fb-contrib:NCMU_NON_COLLECTION_METHOD_USE2

fb-contribNCMU_NON_COLLECTION_METHOD_USEINFO
G
fb-contrib:PME_POOR_MANS_ENUM&

fb-contribPME_POOR_MANS_ENUMINFO
n
0fb-contrib:SPP_NULL_CHECK_ON_MAP_SUBSET_ACCESSOR:

fb-contrib%SPP_NULL_CHECK_ON_MAP_SUBSET_ACCESSORMAJOR
_
)fb-contrib:CBC_CONTAINS_BASED_CONDITIONAL2

fb-contribCBC_CONTAINS_BASED_CONDITIONALINFO
[
'fb-contrib:OPM_OVERLY_PERMISSIVE_METHOD0

fb-contribOPM_OVERLY_PERMISSIVE_METHODINFO
~
8fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_NULLB

fb-contrib-UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_NULLMAJOR
]
(fb-contrib:IMC_IMMATURE_CLASS_NO_PACKAGE1

fb-contribIMC_IMMATURE_CLASS_NO_PACKAGEINFO
J
fb-contrib:MDM_THREAD_FAIRNESS(

fb-contribMDM_THREAD_FAIRNESSMAJOR
v
4fb-contrib:SCSS_SUSPICIOUS_CLUSTERED_SESSION_SUPPORT>

fb-contrib)SCSS_SUSPICIOUS_CLUSTERED_SESSION_SUPPORTMAJOR
V
$fb-contrib:FCBL_FIELD_COULD_BE_LOCAL.

fb-contribFCBL_FIELD_COULD_BE_LOCALMAJOR
n
0fb-contrib:MUC_MODIFYING_UNMODIFIABLE_COLLECTION:

fb-contrib%MUC_MODIFYING_UNMODIFIABLE_COLLECTIONMAJOR
Z
&fb-contrib:NAB_NEEDLESS_BOXING_VALUEOF0

fb-contribNAB_NEEDLESS_BOXING_VALUEOFMAJOR
n
0fb-contrib:SCI_SYNCHRONIZED_COLLECTION_ITERATORS:

fb-contrib%SCI_SYNCHRONIZED_COLLECTION_ITERATORSMAJOR
G
fb-contrib:SPP_TEMPORARY_TRIM&

fb-contribSPP_TEMPORARY_TRIMINFO
h
-fb-contrib:SPP_WRONG_COMMONS_TO_STRING_OBJECT7

fb-contrib"SPP_WRONG_COMMONS_TO_STRING_OBJECTMAJOR
ƒ
9fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_IMPOSSIBLE_NULLF

fb-contrib.UTAO_TESTNG_ASSERTION_ODDITIES_IMPOSSIBLE_NULLCRITICAL
H
fb-contrib:SPP_EQUALS_ON_ENUM'

fb-contribSPP_EQUALS_ON_ENUMMAJOR
C
fb-contrib:BL_BURYING_LOGIC$

fb-contribBL_BURYING_LOGICINFO
a
*fb-contrib:SPP_SERIALVER_SHOULD_BE_PRIVATE3

fb-contribSPP_SERIALVER_SHOULD_BE_PRIVATEINFO
X
%fb-contrib:STS_SPURIOUS_THREAD_STATES/

fb-contribSTS_SPURIOUS_THREAD_STATESMAJOR
L
fb-contrib:IOI_COPY_WITH_READER)

fb-contribIOI_COPY_WITH_READERMAJOR
N
 fb-contrib:MDM_BIGDECIMAL_EQUALS*

fb-contribMDM_BIGDECIMAL_EQUALSMAJOR
]
(fb-contrib:NOS_NON_OWNED_SYNCHRONIZATION1

fb-contribNOS_NON_OWNED_SYNCHRONIZATIONINFO
x
5fb-contrib:HCP_HTTP_REQUEST_RESOURCES_NOT_FREED_LOCAL?

fb-contrib*HCP_HTTP_REQUEST_RESOURCES_NOT_FREED_LOCALMAJOR
J
fb-contrib:SPP_NO_CHAR_SB_CTOR(

fb-contribSPP_NO_CHAR_SB_CTORMAJOR
I
fb-contrib:SPP_USE_GETPROPERTY'

fb-contribSPP_USE_GETPROPERTYINFO
_
)fb-contrib:IMC_IMMATURE_CLASS_NO_HASHCODE2

fb-contribIMC_IMMATURE_CLASS_NO_HASHCODEINFO
f
,fb-contrib:SGSU_SUSPICIOUS_GETTER_SETTER_USE6

fb-contrib!SGSU_SUSPICIOUS_GETTER_SETTER_USEMAJOR
Y
&fb-contrib:UTWR_USE_TRY_WITH_RESOURCES/

fb-contribUTWR_USE_TRY_WITH_RESOURCESINFO
`
)fb-contrib:LO_EXCEPTION_WITH_LOGGER_PARMS3

fb-contribLO_EXCEPTION_WITH_LOGGER_PARMSMAJOR
`
)fb-contrib:SCA_SUSPICIOUS_CLONE_ALGORITHM3

fb-contribSCA_SUSPICIOUS_CLONE_ALGORITHMMAJOR
[
'fb-contrib:TBP_TRISTATE_BOOLEAN_PATTERN0

fb-contribTBP_TRISTATE_BOOLEAN_PATTERNINFO
Y
&fb-contrib:SCR_SLOPPY_CLASS_REFLECTION/

fb-contribSCR_SLOPPY_CLASS_REFLECTIONINFO
b
*fb-contrib:SEO_SUBOPTIMAL_EXPRESSION_ORDER4

fb-contribSEO_SUBOPTIMAL_EXPRESSION_ORDERMAJOR
C
fb-contrib:UTA_USE_TO_ARRAY$

fb-contribUTA_USE_TO_ARRAYINFO
h
-fb-contrib:AFBR_ABNORMAL_FINALLY_BLOCK_RETURN7

fb-contrib"AFBR_ABNORMAL_FINALLY_BLOCK_RETURNMAJOR
b
*fb-contrib:S508C_NON_ACCESSIBLE_JCOMPONENT4

fb-contribS508C_NON_ACCESSIBLE_JCOMPONENTMAJOR
\
'fb-contrib:PDP_POORLY_DEFINED_PARAMETER1

fb-contribPDP_POORLY_DEFINED_PARAMETERMAJOR
f
,fb-contrib:ROOM_REFLECTION_ON_OBJECT_METHODS6

fb-contrib!ROOM_REFLECTION_ON_OBJECT_METHODSMAJOR
e
,fb-contrib:ACEM_ABSTRACT_CLASS_EMPTY_METHODS5

fb-contrib!ACEM_ABSTRACT_CLASS_EMPTY_METHODSINFO
L
fb-contrib:UJM_UNJITABLE_METHOD)

fb-contribUJM_UNJITABLE_METHODMAJOR
D
fb-contrib:MDM_THREAD_YIELD%

fb-contribMDM_THREAD_YIELDMAJOR
z
6fb-contrib:OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL@

fb-contrib+OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULLMAJOR
D
fb-contrib:S508C_NO_SETSIZE%

fb-contribS508C_NO_SETSIZEMAJOR
Z
&fb-contrib:DLC_DUBIOUS_LIST_COLLECTION0

fb-contribDLC_DUBIOUS_LIST_COLLECTIONMAJOR
N
 fb-contrib:MAC_MANUAL_ARRAY_COPY*

fb-contribMAC_MANUAL_ARRAY_COPYMAJOR
`
)fb-contrib:SPP_INVALID_BOOLEAN_NULL_CHECK3

fb-contribSPP_INVALID_BOOLEAN_NULL_CHECKMAJOR
ƒ
;fb-contrib:IMC_IMMATURE_CLASS_IDE_GENERATED_PARAMETER_NAMESD

fb-contrib0IMC_IMMATURE_CLASS_IDE_GENERATED_PARAMETER_NAMESINFO
B
fb-contrib:SIL_SQL_IN_LOOP$

fb-contribSIL_SQL_IN_LOOPMAJOR
\
'fb-contrib:SPP_INVALID_CALENDAR_COMPARE1

fb-contribSPP_INVALID_CALENDAR_COMPAREMAJOR
L
fb-contrib:MDM_SETDEFAULTLOCALE)

fb-contribMDM_SETDEFAULTLOCALEMAJOR
r
2fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERT<

fb-contrib'UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERTMAJOR
†
<fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_NOT_NULLF

fb-contrib1UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_NOT_NULLMAJOR
h
-fb-contrib:CRF_CONFLATING_RESOURCES_AND_FILES7

fb-contrib"CRF_CONFLATING_RESOURCES_AND_FILESMAJOR
l
/fb-contrib:PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS9

fb-contrib$PRMC_POSSIBLY_REDUNDANT_METHOD_CALLSMAJOR
N
 fb-contrib:SPP_USE_MATH_CONSTANT*

fb-contribSPP_USE_MATH_CONSTANTMAJOR
b
*fb-contrib:UNNC_UNNECESSARY_NEW_NULL_CHECK4

fb-contribUNNC_UNNECESSARY_NEW_NULL_CHECKMAJOR
v
4fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_ASSERT_USED>

fb-contrib)UTAO_JUNIT_ASSERTION_ODDITIES_ASSERT_USEDMAJOR
Q
"fb-contrib:WEM_OBSCURING_EXCEPTION+

fb-contribWEM_OBSCURING_EXCEPTIONINFO
x
5fb-contrib:JXI_UNDEFINED_PARAMETER_SOURCE_IN_ENDPOINT?

fb-contrib*JXI_UNDEFINED_PARAMETER_SOURCE_IN_ENDPOINTMAJOR
N
 fb-contrib:LO_TOSTRING_PARAMETER*

fb-contribLO_TOSTRING_PARAMETERMAJOR
T
#fb-contrib:SPP_STUTTERED_ASSIGNMENT-

fb-contribSPP_STUTTERED_ASSIGNMENTMAJOR
A
fb-contrib:UAA_USE_ADD_ALL#

fb-contribUAA_USE_ADD_ALLINFO
\
'fb-contrib:BAS_BLOATED_ASSIGNMENT_SCOPE1

fb-contribBAS_BLOATED_ASSIGNMENT_SCOPEMAJOR
f
,fb-contrib:LO_INVALID_STRING_FORMAT_NOTATION6

fb-contrib!LO_INVALID_STRING_FORMAT_NOTATIONMAJOR
j
.fb-contrib:CVAA_CONTRAVARIANT_ARRAY_ASSIGNMENT8

fb-contrib#CVAA_CONTRAVARIANT_ARRAY_ASSIGNMENTMAJOR
V
$fb-contrib:NAB_NEEDLESS_BOXING_PARSE.

fb-contribNAB_NEEDLESS_BOXING_PARSEMAJOR
}
8fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_ACTUAL_CONSTANTA

fb-contrib-UTAO_JUNIT_ASSERTION_ODDITIES_ACTUAL_CONSTANTINFO
{
7fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_INEXACT_DOUBLE@

fb-contrib,UTAO_JUNIT_ASSERTION_ODDITIES_INEXACT_DOUBLEINFO
S
#fb-contrib:CC_CYCLOMATIC_COMPLEXITY,

fb-contribCC_CYCLOMATIC_COMPLEXITYINFO
`
)fb-contrib:ITU_INAPPROPRIATE_TOSTRING_USE3

fb-contribITU_INAPPROPRIATE_TOSTRING_USEMAJOR
T
#fb-contrib:SPP_STATIC_FORMAT_STRING-

fb-contribSPP_STATIC_FORMAT_STRINGMAJOR
a
*fb-contrib:CNC_COLLECTION_NAMING_CONFUSION3

fb-contribCNC_COLLECTION_NAMING_CONFUSIONINFO
j
.fb-contrib:FCCD_FIND_CLASS_CIRCULAR_DEPENDENCY8

fb-contrib#FCCD_FIND_CLASS_CIRCULAR_DEPENDENCYMAJOR
<
fb-contrib:SPP_USE_GET0!

fb-contribSPP_USE_GET0MAJOR
^
(fb-contrib:DWI_MODIFYING_WHILE_ITERATING2

fb-contribDWI_MODIFYING_WHILE_ITERATINGMAJOR
\
'fb-contrib:MDM_PROMISCUOUS_SERVERSOCKET1

fb-contribMDM_PROMISCUOUS_SERVERSOCKETMAJOR
T
#fb-contrib:SPP_NEGATIVE_BITSET_ITEM-

fb-contribSPP_NEGATIVE_BITSET_ITEMMAJOR
J
fb-contrib:SPP_USELESS_TERNARY(

fb-contribSPP_USELESS_TERNARYMAJOR
_
)fb-contrib:IMC_IMMATURE_CLASS_LOWER_CLASS2

fb-contribIMC_IMMATURE_CLASS_LOWER_CLASSINFO
B
fb-contrib:SG_SLUGGISH_GUI$

fb-contribSG_SLUGGISH_GUIMAJOR
\
'fb-contrib:DWI_DELETING_WHILE_ITERATING1

fb-contribDWI_DELETING_WHILE_ITERATINGMAJOR
X
%fb-contrib:ISB_EMPTY_STRING_APPENDING/

fb-contribISB_EMPTY_STRING_APPENDINGMAJOR
`
)fb-contrib:CCNE_COMPARE_CLASS_EQUALS_NAME3

fb-contribCCNE_COMPARE_CLASS_EQUALS_NAMEMAJOR
n
0fb-contrib:CSBTS_COMMONS_STRING_BUILDER_TOSTRING:

fb-contrib%CSBTS_COMMONS_STRING_BUILDER_TOSTRINGMAJOR
l
/fb-contrib:LO_LOGGER_LOST_EXCEPTION_STACK_TRACE9

fb-contrib$LO_LOGGER_LOST_EXCEPTION_STACK_TRACEMAJOR
b
*fb-contrib:SNG_SUSPICIOUS_NULL_FIELD_GUARD4

fb-contribSNG_SUSPICIOUS_NULL_FIELD_GUARDMAJOR
n
0fb-contrib:CVAA_CONTRAVARIANT_ELEMENT_ASSIGNMENT:

fb-contrib%CVAA_CONTRAVARIANT_ELEMENT_ASSIGNMENTMAJOR
m
0fb-contrib:DTEP_DEPRECATED_TYPESAFE_ENUM_PATTERN9

fb-contrib%DTEP_DEPRECATED_TYPESAFE_ENUM_PATTERNINFO
L
fb-contrib:S508C_SET_COMP_COLOR)

fb-contribS508C_SET_COMP_COLORMAJOR
X
%fb-contrib:DMC_DUBIOUS_MAP_COLLECTION/

fb-contribDMC_DUBIOUS_MAP_COLLECTIONMAJOR
P
!fb-contrib:SPP_TOSTRING_ON_STRING+

fb-contribSPP_TOSTRING_ON_STRINGMAJOR
k
/fb-contrib:USBR_UNNECESSARY_STORE_BEFORE_RETURN8

fb-contrib$USBR_UNNECESSARY_STORE_BEFORE_RETURNINFO
]
(fb-contrib:LSC_LITERAL_STRING_COMPARISON1

fb-contribLSC_LITERAL_STRING_COMPARISONINFO
r
2fb-contrib:UCPM_USE_CHARACTER_PARAMETERIZED_METHOD<

fb-contrib'UCPM_USE_CHARACTER_PARAMETERIZED_METHODMAJOR
}
8fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_BOOLEAN_ASSERTA

fb-contrib-UTAO_TESTNG_ASSERTION_ODDITIES_BOOLEAN_ASSERTINFO
\
'fb-contrib:LO_INVALID_FORMATTING_ANCHOR1

fb-contribLO_INVALID_FORMATTING_ANCHORMAJOR
\
'fb-contrib:SPP_DOUBLE_APPENDED_LITERALS1

fb-contribSPP_DOUBLE_APPENDED_LITERALSMAJOR
p
1fb-contrib:UMTP_UNBOUND_METHOD_TEMPLATE_PARAMETER;

fb-contrib&UMTP_UNBOUND_METHOD_TEMPLATE_PARAMETERMAJOR
X
%fb-contrib:DDC_DOUBLE_DATE_COMPARISON/

fb-contribDDC_DOUBLE_DATE_COMPARISONMAJOR
f
,fb-contrib:JPAI_NON_PROXIED_TRANSACTION_CALL6

fb-contrib!JPAI_NON_PROXIED_TRANSACTION_CALLMAJOR
b
*fb-contrib:NAB_NEEDLESS_AUTOBOXING_VALUEOF4

fb-contribNAB_NEEDLESS_AUTOBOXING_VALUEOFMAJOR
„
;fb-contrib:CCI_CONCURRENT_COLLECTION_ISSUES_USE_PUT_IS_RACYE

fb-contrib0CCI_CONCURRENT_COLLECTION_ISSUES_USE_PUT_IS_RACYMAJOR
v
4fb-contrib:HES_EXECUTOR_OVERWRITTEN_WITHOUT_SHUTDOWN>

fb-contrib)HES_EXECUTOR_OVERWRITTEN_WITHOUT_SHUTDOWNMAJOR
Y
&fb-contrib:MRC_METHOD_RETURNS_CONSTANT/

fb-contribMRC_METHOD_RETURNS_CONSTANTINFO
\
'fb-contrib:NAB_NEEDLESS_AUTOBOXING_CTOR1

fb-contribNAB_NEEDLESS_AUTOBOXING_CTORMAJOR
b
*fb-contrib:NIR_NEEDLESS_INSTANCE_RETRIEVAL4

fb-contribNIR_NEEDLESS_INSTANCE_RETRIEVALMAJOR
t
3fb-contrib:CHTH_COMMONS_HASHCODE_BUILDER_TOHASHCODE=

fb-contrib(CHTH_COMMONS_HASHCODE_BUILDER_TOHASHCODEMAJOR
_
)fb-contrib:DRE_DECLARED_RUNTIME_EXCEPTION2

fb-contribDRE_DECLARED_RUNTIME_EXCEPTIONINFO
T
#fb-contrib:JVR_JDBC_VENDOR_RELIANCE-

fb-contribJVR_JDBC_VENDOR_RELIANCEMAJOR
~
8fb-contrib:CSI_CHAR_SET_ISSUES_USE_STANDARD_CHARSET_NAMEB

fb-contrib-CSI_CHAR_SET_ISSUES_USE_STANDARD_CHARSET_NAMEMAJOR
j
.fb-contrib:SACM_STATIC_ARRAY_CREATED_IN_METHOD8

fb-contrib#SACM_STATIC_ARRAY_CREATED_IN_METHODMAJOR
t
3fb-contrib:SCRV_SUSPICIOUS_COMPARATOR_RETURN_VALUES=

fb-contrib(SCRV_SUSPICIOUS_COMPARATOR_RETURN_VALUESMAJOR
h
-fb-contrib:AIOB_ARRAY_STORE_TO_NULL_REFERENCE7

fb-contrib"AIOB_ARRAY_STORE_TO_NULL_REFERENCEMAJOR
c
+fb-contrib:CFS_CONFUSING_FUNCTION_SEMANTICS4

fb-contrib CFS_CONFUSING_FUNCTION_SEMANTICSINFO
]
(fb-contrib:OCP_OVERLY_CONCRETE_PARAMETER1

fb-contribOCP_OVERLY_CONCRETE_PARAMETERINFO
`
)fb-contrib:AOM_ABSTRACT_OVERRIDDEN_METHOD3

fb-contribAOM_ABSTRACT_OVERRIDDEN_METHODMAJOR
E
fb-contrib:PL_PARALLEL_LISTS%

fb-contribPL_PARALLEL_LISTSINFO
s
3fb-contrib:SCII_SPOILED_CHILD_INTERFACE_IMPLEMENTOR<

fb-contrib(SCII_SPOILED_CHILD_INTERFACE_IMPLEMENTORINFO
b
*fb-contrib:DSOC_DUBIOUS_SET_OF_COLLECTIONS4

fb-contribDSOC_DUBIOUS_SET_OF_COLLECTIONSMAJOR
t
3fb-contrib:LO_INCORRECT_NUMBER_OF_ANCHOR_PARAMETERS=

fb-contrib(LO_INCORRECT_NUMBER_OF_ANCHOR_PARAMETERSMAJOR
v
4fb-contrib:OI_OPTIONAL_ISSUES_USES_DELAYED_EXECUTION>

fb-contrib)OI_OPTIONAL_ISSUES_USES_DELAYED_EXECUTIONMAJOR
†
<fb-contrib:JPAI_NON_SPECIFIED_TRANSACTION_EXCEPTION_HANDLINGF

fb-contrib1JPAI_NON_SPECIFIED_TRANSACTION_EXCEPTION_HANDLINGMAJOR
h
-fb-contrib:LSYC_LOCAL_SYNCHRONIZED_COLLECTION7

fb-contrib"LSYC_LOCAL_SYNCHRONIZED_COLLECTIONMAJOR
\
'fb-contrib:SPP_STRINGBUILDER_IS_MUTABLE1

fb-contribSPP_STRINGBUILDER_IS_MUTABLEMAJOR
c
+fb-contrib:CU_CLONE_USABILITY_OBJECT_RETURN4

fb-contrib CU_CLONE_USABILITY_OBJECT_RETURNINFO
H
fb-contrib:SPP_NON_ARRAY_PARM'

fb-contribSPP_NON_ARRAY_PARMMAJOR
e
,fb-contrib:UCC_UNRELATED_COLLECTION_CONTENTS5

fb-contrib!UCC_UNRELATED_COLLECTION_CONTENTSINFO
t
3fb-contrib:CSI_CHAR_SET_ISSUES_USE_STANDARD_CHARSET=

fb-contrib(CSI_CHAR_SET_ISSUES_USE_STANDARD_CHARSETMAJOR
X
%fb-contrib:HES_LOCAL_EXECUTOR_SERVICE/

fb-contribHES_LOCAL_EXECUTOR_SERVICEMAJOR
h
-fb-contrib:JXI_INVALID_CONTEXT_PARAMETER_TYPE7

fb-contrib"JXI_INVALID_CONTEXT_PARAMETER_TYPEMAJOR
m
0fb-contrib:AWCBR_ARRAY_WRAPPED_CALL_BY_REFERENCE9

fb-contrib%AWCBR_ARRAY_WRAPPED_CALL_BY_REFERENCEINFO
Q
"fb-contrib:STT_TOSTRING_MAP_KEYING+

fb-contribSTT_TOSTRING_MAP_KEYINGINFO
ˆ
=fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NOT_NULLG

fb-contrib2UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NOT_NULLMAJOR
\
'fb-contrib:SPP_EQUALS_ON_STRING_BUILDER1

fb-contribSPP_EQUALS_ON_STRING_BUILDERMAJOR
P
!fb-contrib:SPP_INTERN_ON_CONSTANT+

fb-contribSPP_INTERN_ON_CONSTANTMAJOR
Y
&fb-contrib:URV_UNRELATED_RETURN_VALUES/

fb-contribURV_UNRELATED_RETURN_VALUESINFO
=
fb-contrib:CE_CLASS_ENVY!

fb-contribCE_CLASS_ENVYINFO
R
"fb-contrib:SPP_SUSPECT_STRING_TEST,

fb-contribSPP_SUSPECT_STRING_TESTMAJOR
b
*fb-contrib:BED_BOGUS_EXCEPTION_DECLARATION4

fb-contribBED_BOGUS_EXCEPTION_DECLARATIONMAJOR
p
1fb-contrib:PUS_POSSIBLE_UNSUSPECTED_SERIALIZATION;

fb-contrib&PUS_POSSIBLE_UNSUSPECTED_SERIALIZATIONMAJOR
X
%fb-contrib:SPP_NULL_BEFORE_INSTANCEOF/

fb-contribSPP_NULL_BEFORE_INSTANCEOFMAJOR
Š
>fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_NOT_EQUALSH

fb-contrib3UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_NOT_EQUALSMAJOR
C
fb-contrib:SPP_EMPTY_CASING$

fb-contribSPP_EMPTY_CASINGINFO
x
5fb-contrib:USFW_UNSYNCHRONIZED_SINGLETON_FIELD_WRITES?

fb-contrib*USFW_UNSYNCHRONIZED_SINGLETON_FIELD_WRITESMAJOR
C
fb-contrib:UVA_USE_VAR_ARGS$

fb-contribUVA_USE_VAR_ARGSINFO
H
fb-contrib:RFI_SET_ACCESSIBLE'

fb-contribRFI_SET_ACCESSIBLEMAJOR
d
+fb-contrib:SPP_CONVERSION_OF_STRING_LITERAL5

fb-contrib SPP_CONVERSION_OF_STRING_LITERALMAJOR
>
fb-contrib:SPP_USE_ISNAN"

fb-contribSPP_USE_ISNANMAJOR
T
#fb-contrib:LO_SUSPECT_LOG_PARAMETER-

fb-contribLO_SUSPECT_LOG_PARAMETERMAJOR
b
*fb-contrib:SJVU_SUSPICIOUS_JDK_VERSION_USE4

fb-contribSJVU_SUSPICIOUS_JDK_VERSION_USEMAJOR
€
9fb-contrib:OI_OPTIONAL_ISSUES_PRIMITIVE_VARIANT_PREFERREDC

fb-contrib.OI_OPTIONAL_ISSUES_PRIMITIVE_VARIANT_PREFERREDMAJOR
{
7fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_BOOLEAN_ASSERT@

fb-contrib,UTAO_JUNIT_ASSERTION_ODDITIES_BOOLEAN_ASSERTINFO
f
,fb-contrib:IICU_INCORRECT_INTERNAL_CLASS_USE6

fb-contrib!IICU_INCORRECT_INTERNAL_CLASS_USEMAJOR
d
+fb-contrib:JXI_PARM_PARAM_NOT_FOUND_IN_PATH5

fb-contrib JXI_PARM_PARAM_NOT_FOUND_IN_PATHMAJOR
F
fb-contrib:TR_TAIL_RECURSION&

fb-contribTR_TAIL_RECURSIONMAJOR
z
6fb-contrib:UAC_UNNECESSARY_API_CONVERSION_FILE_TO_PATH@

fb-contrib+UAC_UNNECESSARY_API_CONVERSION_FILE_TO_PATHMAJOR
„
;fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_EQUALSE

fb-contrib0UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_EQUALSMAJOR
X
%fb-contrib:CTU_CONFLICTING_TIME_UNITS/

fb-contribCTU_CONFLICTING_TIME_UNITSMAJOR
k
/fb-contrib:CU_CLONE_USABILITY_MISMATCHED_RETURN8

fb-contrib$CU_CLONE_USABILITY_MISMATCHED_RETURNINFO
f
,fb-contrib:JXI_GET_ENDPOINT_CONSUMES_CONTENT6

fb-contrib!JXI_GET_ENDPOINT_CONSUMES_CONTENTMAJOR
p
1fb-contrib:BED_HIERARCHICAL_EXCEPTION_DECLARATION;

fb-contrib&BED_HIERARCHICAL_EXCEPTION_DECLARATIONMAJOR
T
#fb-contrib:FPL_FLOATING_POINT_LOOPS-

fb-contribFPL_FLOATING_POINT_LOOPSMAJOR
`
)fb-contrib:AIOB_ARRAY_INDEX_OUT_OF_BOUNDS3

fb-contribAIOB_ARRAY_INDEX_OUT_OF_BOUNDSMAJOR
Œ
?fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NOT_EQUALSI

fb-contrib4UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NOT_EQUALSMAJOR
T
#fb-contrib:WI_DUPLICATE_WIRED_TYPES-

fb-contribWI_DUPLICATE_WIRED_TYPESMAJOR
U
$fb-contrib:CU_CLONE_USABILITY_THROWS-

fb-contribCU_CLONE_USABILITY_THROWSINFO
x
5fb-contrib:PCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP?

fb-contrib*PCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOPMAJOR
I
fb-contrib:UP_UNUSED_PARAMETER'

fb-contribUP_UNUSED_PARAMETERINFO
N
 fb-contrib:ODN_ORPHANED_DOM_NODE*

fb-contribODN_ORPHANED_DOM_NODEMAJOR
O
!fb-contrib:URV_CHANGE_RETURN_TYPE*

fb-contribURV_CHANGE_RETURN_TYPEINFO
d
+fb-contrib:JPAI_HC_EQUALS_ON_MANAGED_ENTITY5

fb-contrib JPAI_HC_EQUALS_ON_MANAGED_ENTITYMAJOR
‚
:fb-contrib:NMCS_NEEDLESS_MEMBER_COLLECTION_SYNCHRONIZATIOND

fb-contrib/NMCS_NEEDLESS_MEMBER_COLLECTION_SYNCHRONIZATIONMAJOR
K
fb-contrib:USS_USE_STRING_SPLIT(

fb-contribUSS_USE_STRING_SPLITINFO
W
%fb-contrib:LII_LIST_INDEXED_ITERATING.

fb-contribLII_LIST_INDEXED_ITERATINGINFO
P
!fb-contrib:OC_OVERZEALOUS_CASTING+

fb-contribOC_OVERZEALOUS_CASTINGMAJOR
x
5fb-contrib:HCP_HTTP_REQUEST_RESOURCES_NOT_FREED_FIELD?

fb-contrib*HCP_HTTP_REQUEST_RESOURCES_NOT_FREED_FIELDMAJOR
n
0fb-contrib:OI_OPTIONAL_ISSUES_CHECKING_REFERENCE:

fb-contrib%OI_OPTIONAL_ISSUES_CHECKING_REFERENCEMAJOR
X
%fb-contrib:SLS_SUSPICIOUS_LOOP_SEARCH/

fb-contribSLS_SUSPICIOUS_LOOP_SEARCHMAJOR
T
#fb-contrib:MDM_SIGNAL_NOT_SIGNALALL-

fb-contribMDM_SIGNAL_NOT_SIGNALALLMAJOR
V
$fb-contrib:PMB_POSSIBLE_MEMORY_BLOAT.

fb-contribPMB_POSSIBLE_MEMORY_BLOATMAJOR
€
9fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NULLC

fb-contrib.UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NULLMAJOR
T
#fb-contrib:MDM_WAIT_WITHOUT_TIMEOUT-

fb-contribMDM_WAIT_WITHOUT_TIMEOUTMAJOR
d
+fb-contrib:SSCU_SUSPICIOUS_SHADED_CLASS_USE5

fb-contrib SSCU_SUSPICIOUS_SHADED_CLASS_USEMAJOR
b
*fb-contrib:WOC_WRITE_ONLY_COLLECTION_LOCAL4

fb-contribWOC_WRITE_ONLY_COLLECTION_LOCALMAJOR
D
fb-contrib:MDM_SECURERANDOM%

fb-contribMDM_SECURERANDOMMAJOR
H
fb-contrib:SPP_USELESS_CASING'

fb-contribSPP_USELESS_CASINGMAJOR
g
-fb-contrib:EXS_EXCEPTION_SOFTENING_NO_CHECKED6

fb-contrib"EXS_EXCEPTION_SOFTENING_NO_CHECKEDINFO
r
2fb-contrib:IPU_IMPROPER_PROPERTIES_USE_SETPROPERTY<

fb-contrib'IPU_IMPROPER_PROPERTIES_USE_SETPROPERTYMAJOR
f
,fb-contrib:NCS_NEEDLESS_CUSTOM_SERIALIZATION6

fb-contrib!NCS_NEEDLESS_CUSTOM_SERIALIZATIONMAJOR
P
!fb-contrib:IOI_DOUBLE_BUFFER_COPY+

fb-contribIOI_DOUBLE_BUFFER_COPYMAJOR
V
$fb-contrib:JPAI_IGNORED_MERGE_RESULT.

fb-contribJPAI_IGNORED_MERGE_RESULTMAJOR
€
9fb-contrib:UAC_UNNECESSARY_API_CONVERSION_DATE_TO_INSTANTC

fb-contrib.UAC_UNNECESSARY_API_CONVERSION_DATE_TO_INSTANTMAJOR
b
*fb-contrib:NAB_NEEDLESS_BOXING_STRING_CTOR4

fb-contribNAB_NEEDLESS_BOXING_STRING_CTORMAJOR
}
8fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_INEXACT_DOUBLEA

fb-contrib-UTAO_TESTNG_ASSERTION_ODDITIES_INEXACT_DOUBLEINFO
\
'fb-contrib:NRTL_NON_RECYCLEABLE_TAG_LIB1

fb-contribNRTL_NON_RECYCLEABLE_TAG_LIBMAJOR
n
0fb-contrib:PIS_POSSIBLE_INCOMPLETE_SERIALIZATION:

fb-contrib%PIS_POSSIBLE_INCOMPLETE_SERIALIZATIONMAJOR
F
fb-contrib:S508C_NULL_LAYOUT&

fb-contribS508C_NULL_LAYOUTMAJOR
l
/fb-contrib:CSI_CHAR_SET_ISSUES_UNKNOWN_ENCODING9

fb-contrib$CSI_CHAR_SET_ISSUES_UNKNOWN_ENCODINGMAJOR
X
%fb-contrib:SPP_NULL_CHECK_ON_OPTIONAL/

fb-contribSPP_NULL_CHECK_ON_OPTIONALMAJOR
`
)fb-contrib:SPP_USE_BIGDECIMAL_STRING_CTOR3

fb-contribSPP_USE_BIGDECIMAL_STRING_CTORMAJOR
\
'fb-contrib:CAAL_CONFUSING_ARRAY_AS_LIST1

fb-contribCAAL_CONFUSING_ARRAY_AS_LISTMAJOR
^
(fb-contrib:ICA_INVALID_CONSTANT_ARGUMENT2

fb-contribICA_INVALID_CONSTANT_ARGUMENTMAJOR
Z
&fb-contrib:IPU_IMPROPER_PROPERTIES_USE0

fb-contribIPU_IMPROPER_PROPERTIES_USEMAJOR
[
'fb-contrib:COM_COPIED_OVERRIDDEN_METHOD0

fb-contribCOM_COPIED_OVERRIDDEN_METHODINFO
@
fb-contrib:SPP_USE_CHARAT#

fb-contribSPP_USE_CHARATMAJOR
Z
&fb-contrib:HES_EXECUTOR_NEVER_SHUTDOWN0

fb-contribHES_EXECUTOR_NEVER_SHUTDOWNMAJOR
j
.fb-contrib:IOI_USE_OF_FILE_STREAM_CONSTRUCTORS8

fb-contrib#IOI_USE_OF_FILE_STREAM_CONSTRUCTORSMAJOR
[
'fb-contrib:IMC_IMMATURE_CLASS_NO_EQUALS0

fb-contribIMC_IMMATURE_CLASS_NO_EQUALSINFO
L
fb-contrib:S508C_NO_SETLABELFOR)

fb-contribS508C_NO_SETLABELFORMAJOR
h
-fb-contrib:SUA_SUSPICIOUS_UNINITIALIZED_ARRAY7

fb-contrib"SUA_SUSPICIOUS_UNINITIALIZED_ARRAYMAJOR
b
*fb-contrib:NPMC_NON_PRODUCTIVE_METHOD_CALL4

fb-contribNPMC_NON_PRODUCTIVE_METHOD_CALLMAJOR
q
2fb-contrib:URV_INHERITED_METHOD_WITH_RELATED_TYPES;

fb-contrib'URV_INHERITED_METHOD_WITH_RELATED_TYPESINFO
i
.fb-contrib:EXS_EXCEPTION_SOFTENING_HAS_CHECKED7

fb-contrib#EXS_EXCEPTION_SOFTENING_HAS_CHECKEDINFO
\
'fb-contrib:JPAI_INEFFICIENT_EAGER_FETCH1

fb-contribJPAI_INEFFICIENT_EAGER_FETCHMAJOR
V
$fb-contrib:MDM_STRING_BYTES_ENCODING.

fb-contribMDM_STRING_BYTES_ENCODINGMAJOR
l
/fb-contrib:CEBE_COMMONS_EQUALS_BUILDER_ISEQUALS9

fb-contrib$CEBE_COMMONS_EQUALS_BUILDER_ISEQUALSMAJOR
o
1fb-contrib:EXS_EXCEPTION_SOFTENING_NO_CONSTRAINTS:

fb-contrib&EXS_EXCEPTION_SOFTENING_NO_CONSTRAINTSINFO

8fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_IMPOSSIBLE_NULLE

fb-contrib-UTAO_JUNIT_ASSERTION_ODDITIES_IMPOSSIBLE_NULLCRITICAL
Z
&fb-contrib:ABC_ARRAY_BASED_COLLECTIONS0

fb-contribABC_ARRAY_BASED_COLLECTIONSMAJOR
c
+fb-contrib:IMC_IMMATURE_CLASS_UPPER_PACKAGE4

fb-contrib IMC_IMMATURE_CLASS_UPPER_PACKAGEINFO
[
'fb-contrib:STT_TOSTRING_STORED_IN_FIELD0

fb-contribSTT_TOSTRING_STORED_IN_FIELDINFO
i
.fb-contrib:IKNC_INCONSISTENT_HTTP_PARAM_CASING7

fb-contrib#IKNC_INCONSISTENT_HTTP_PARAM_CASINGINFO
K
fb-contrib:LO_STUTTERED_MESSAGE(

fb-contribLO_STUTTERED_MESSAGEINFO
k
/fb-contrib:EXS_EXCEPTION_SOFTENING_RETURN_FALSE8

fb-contrib$EXS_EXCEPTION_SOFTENING_RETURN_FALSEINFO
Q
"fb-contrib:SPP_NON_USEFUL_TOSTRING+

fb-contribSPP_NON_USEFUL_TOSTRINGINFO
U
$fb-contrib:COM_PARENT_DELEGATED_CALL-

fb-contribCOM_PARENT_DELEGATED_CALLINFO
n
0fb-contrib:JPAI_TRANSACTION_ON_NON_PUBLIC_METHOD:

fb-contrib%JPAI_TRANSACTION_ON_NON_PUBLIC_METHODMAJOR
V
$fb-contrib:NAB_NEEDLESS_BOX_TO_UNBOX.

fb-contribNAB_NEEDLESS_BOX_TO_UNBOXMAJOR
L
fb-contrib:LO_SUSPECT_LOG_CLASS)

fb-contribLO_SUSPECT_LOG_CLASSMAJOR
b
*fb-contrib:PMB_INSTANCE_BASED_THREAD_LOCAL4

fb-contribPMB_INSTANCE_BASED_THREAD_LOCALMAJOR
W
%fb-contrib:STT_STRING_PARSING_A_FIELD.

fb-contribSTT_STRING_PARSING_A_FIELDINFO
T
#fb-contrib:MDM_RUNTIME_EXIT_OR_HALT-

fb-contribMDM_RUNTIME_EXIT_OR_HALTMAJOR

9fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_ACTUAL_CONSTANTB

fb-contrib.UTAO_TESTNG_ASSERTION_ODDITIES_ACTUAL_CONSTANTINFO
`
)fb-contrib:BSB_BLOATED_SYNCHRONIZED_BLOCK3

fb-contribBSB_BLOATED_SYNCHRONIZED_BLOCKMAJOR
o
1fb-contrib:SMII_STATIC_METHOD_INSTANCE_INVOCATION:

fb-contrib&SMII_STATIC_METHOD_INSTANCE_INVOCATIONINFO
‚
:fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_EQUALSD

fb-contrib/UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_EQUALSMAJOR
P
!fb-contrib:ISB_TOSTRING_APPENDING+

fb-contribISB_TOSTRING_APPENDINGMAJOR
t
3fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_NO_ASSERT=

fb-contrib(UTAO_TESTNG_ASSERTION_ODDITIES_NO_ASSERTMAJOR
t
3fb-contrib:PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS=

fb-contrib(PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESSMAJOR
Y
&fb-contrib:SEC_SIDE_EFFECT_CONSTRUCTOR/

fb-contribSEC_SIDE_EFFECT_CONSTRUCTORINFO
b
*fb-contrib:SNG_SUSPICIOUS_NULL_LOCAL_GUARD4

fb-contribSNG_SUSPICIOUS_NULL_LOCAL_GUARDMAJOR
^
(fb-contrib:LGO_LINGERING_GRAPHICS_OBJECT2

fb-contribLGO_LINGERING_GRAPHICS_OBJECTMAJOR
j
.fb-contrib:LO_APPENDED_STRING_IN_FORMAT_STRING8

fb-contrib#LO_APPENDED_STRING_IN_FORMAT_STRINGMAJOR
K
fb-contrib:CBX_CUSTOM_BUILT_XML(

fb-contribCBX_CUSTOM_BUILT_XMLINFO
J
fb-contrib:MDM_RUNFINALIZATION(

fb-contribMDM_RUNFINALIZATIONMAJOR
]
(fb-contrib:MOM_MISLEADING_OVERLOAD_MODEL1

fb-contribMOM_MISLEADING_OVERLOAD_MODELINFO
I
fb-contrib:FP_FINAL_PARAMETERS'

fb-contribFP_FINAL_PARAMETERSINFO
h
-fb-contrib:SPP_STRINGBUFFER_WITH_EMPTY_STRING7

fb-contrib"SPP_STRINGBUFFER_WITH_EMPTY_STRINGMAJOR
j
.fb-contrib:CAO_CONFUSING_AUTOBOXED_OVERLOADING8

fb-contrib#CAO_CONFUSING_AUTOBOXED_OVERLOADINGMAJOR
†
<fb-contrib:LO_EMBEDDED_SIMPLE_STRING_FORMAT_IN_FORMAT_STRINGF

fb-contrib1LO_EMBEDDED_SIMPLE_STRING_FORMAT_IN_FORMAT_STRINGMAJOR
t
3fb-contrib:NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION=

fb-contrib(NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSIONMAJOR
k
/fb-contrib:IMC_IMMATURE_CLASS_WRONG_FIELD_ORDER8

fb-contrib$IMC_IMMATURE_CLASS_WRONG_FIELD_ORDERINFO
z
6fb-contrib:OI_OPTIONAL_ISSUES_USES_IMMEDIATE_EXECUTION@

fb-contrib+OI_OPTIONAL_ISSUES_USES_IMMEDIATE_EXECUTIONMAJOR
T
#fb-contrib:NAB_NEEDLESS_BOX_TO_CAST-

fb-contribNAB_NEEDLESS_BOX_TO_CASTMAJOR
x
5fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_ASSERT_USED?

fb-contrib*UTAO_TESTNG_ASSERTION_ODDITIES_ASSERT_USEDMAJOR
b
*fb-contrib:WOC_WRITE_ONLY_COLLECTION_FIELD4

fb-contribWOC_WRITE_ONLY_COLLECTION_FIELDMAJOR
R
"fb-contrib:CLI_CONSTANT_LIST_INDEX,

fb-contribCLI_CONSTANT_LIST_INDEXMAJOR
g
-fb-contrib:IMC_IMMATURE_CLASS_PRINTSTACKTRACE6

fb-contrib"IMC_IMMATURE_CLASS_PRINTSTACKTRACEINFO
R
"fb-contrib:PSC_PRESIZE_COLLECTIONS,

fb-contribPSC_PRESIZE_COLLECTIONSMAJOR
q
2fb-contrib:IKNC_INCONSISTENT_HTTP_ATTRIBUTE_CASING;

fb-contrib'IKNC_INCONSISTENT_HTTP_ATTRIBUTE_CASINGINFO
€
9fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_USING_DEPRECATEDC

fb-contrib.UTAO_JUNIT_ASSERTION_ODDITIES_USING_DEPRECATEDMAJOR