
R
"findsecbugs:SPRING_FILE_DISCLOSURE,
findsecbugsSPRING_FILE_DISCLOSUREMAJOR
V
$findsecbugs:WEAK_MESSAGE_DIGEST_SHA1.
findsecbugsWEAK_MESSAGE_DIGEST_SHA1MAJOR
J
findsecbugs:HARD_CODE_PASSWORD(
findsecbugsHARD_CODE_PASSWORDMAJOR
<
findsecbugs:NULL_CIPHER!
findsecbugsNULL_CIPHERMAJOR
L
findsecbugs:XSS_REQUEST_WRAPPER)
findsecbugsXSS_REQUEST_WRAPPERMAJOR
H
findsecbugs:COOKIE_PERSISTENT'
findsecbugsCOOKIE_PERSISTENTMAJOR
P
!findsecbugs:CUSTOM_MESSAGE_DIGEST+
findsecbugsCUSTOM_MESSAGE_DIGESTMAJOR
X
%findsecbugs:PLAY_UNVALIDATED_REDIRECT/
findsecbugsPLAY_UNVALIDATED_REDIRECTMAJOR
Q
 findsecbugs:LDAP_ENTRY_POISONING-
findsecbugsLDAP_ENTRY_POISONINGCRITICAL
Q
"findsecbugs:SERVLET_HEADER_REFERER+
findsecbugsSERVLET_HEADER_REFERERINFO
v
4findsecbugs:SPRING_CSRF_UNRESTRICTED_REQUEST_MAPPING>
findsecbugs(SPRING_CSRF_UNRESTRICTED_REQUEST_MAPPINGMAJOR
@
findsecbugs:HARD_CODE_KEY#
findsecbugsHARD_CODE_KEYMAJOR
E
findsecbugs:SPEL_INJECTION'
findsecbugsSPEL_INJECTIONCRITICAL
D
findsecbugs:PERMISSIVE_CORS%
findsecbugsPERMISSIVE_CORSMAJOR
G
findsecbugs:TAPESTRY_ENDPOINT&
findsecbugsTAPESTRY_ENDPOINTINFO
T
#findsecbugs:WEAK_MESSAGE_DIGEST_MD5-
findsecbugsWEAK_MESSAGE_DIGEST_MD5MAJOR
S
#findsecbugs:HTTP_RESPONSE_SPLITTING,
findsecbugsHTTP_RESPONSE_SPLITTINGINFO
J
findsecbugs:PATH_TRAVERSAL_OUT(
findsecbugsPATH_TRAVERSAL_OUTMAJOR
M
findsecbugs:SEAM_LOG_INJECTION+
findsecbugsSEAM_LOG_INJECTIONCRITICAL
B
findsecbugs:RSA_NO_PADDING$
findsecbugsRSA_NO_PADDINGMAJOR
@
findsecbugs:URL_REWRITING#
findsecbugsURL_REWRITINGMAJOR
J
findsecbugs:WEAK_TRUST_MANAGER(
findsecbugsWEAK_TRUST_MANAGERMAJOR
o
1findsecbugs:ANDROID_WEB_VIEW_JAVASCRIPT_INTERFACE:
findsecbugs%ANDROID_WEB_VIEW_JAVASCRIPT_INTERFACEINFO
D
findsecbugs:INSECURE_COOKIE%
findsecbugsINSECURE_COOKIEMAJOR
0
findsecbugs:REDOS
findsecbugsREDOSMAJOR
H
findsecbugs:BLOWFISH_KEY_SIZE'
findsecbugsBLOWFISH_KEY_SIZEMAJOR
U
"findsecbugs:OBJECT_DESERIALIZATION/
findsecbugsOBJECT_DESERIALIZATIONCRITICAL
c
)findsecbugs:TEMPLATE_INJECTION_FREEMARKER6
findsecbugsTEMPLATE_INJECTION_FREEMARKERCRITICAL
E
findsecbugs:LDAP_INJECTION'
findsecbugsLDAP_INJECTIONCRITICAL
A
findsecbugs:SERVLET_HEADER#
findsecbugsSERVLET_HEADERINFO
K
findsecbugs:SQL_INJECTION_JPA*
findsecbugsSQL_INJECTION_JPACRITICAL
L
findsecbugs:BAD_HEXA_CONVERSION)
findsecbugsBAD_HEXA_CONVERSIONMAJOR
e
*findsecbugs:JACKSON_UNSAFE_DESERIALIZATION7
findsecbugsJACKSON_UNSAFE_DESERIALIZATIONCRITICAL
<
findsecbugs:XSS_SERVLET!
findsecbugsXSS_SERVLETMAJOR
S
!findsecbugs:SQL_INJECTION_ANDROID.
findsecbugsSQL_INJECTION_ANDROIDCRITICAL
8
findsecbugs:STATIC_IV
findsecbugs	STATIC_IVMAJOR
C
findsecbugs:WICKET_ENDPOINT$
findsecbugsWICKET_ENDPOINTINFO
K
findsecbugs:CRLF_INJECTION_LOGS(
findsecbugsCRLF_INJECTION_LOGSINFO
X
%findsecbugs:UNENCRYPTED_SERVER_SOCKET/
findsecbugsUNENCRYPTED_SERVER_SOCKETMAJOR
?
findsecbugs:XML_DECODER$
findsecbugsXML_DECODERCRITICAL
8
findsecbugs:DES_USAGE
findsecbugs	DES_USAGEMAJOR
[
%findsecbugs:SQL_INJECTION_SPRING_JDBC2
findsecbugsSQL_INJECTION_SPRING_JDBCCRITICAL
J
findsecbugs:UNENCRYPTED_SOCKET(
findsecbugsUNENCRYPTED_SOCKETMAJOR
K
findsecbugs:ANDROID_GEOLOCATION(
findsecbugsANDROID_GEOLOCATIONINFO
Q
"findsecbugs:DESERIALIZATION_GADGET+
findsecbugsDESERIALIZATION_GADGETINFO
C
findsecbugs:SQL_INJECTION&
findsecbugsSQL_INJECTIONCRITICAL
K
findsecbugs:COMMAND_INJECTION*
findsecbugsCOMMAND_INJECTIONCRITICAL
\
'findsecbugs:SPRING_UNVALIDATED_REDIRECT1
findsecbugsSPRING_UNVALIDATED_REDIRECTMAJOR
Q
"findsecbugs:STRUTS_FORM_VALIDATION+
findsecbugsSTRUTS_FORM_VALIDATIONINFO
Y
&findsecbugs:FORMAT_STRING_MANIPULATION/
findsecbugsFORMAT_STRING_MANIPULATIONINFO
C
findsecbugs:SPRING_ENDPOINT$
findsecbugsSPRING_ENDPOINTINFO
C
findsecbugs:XXE_XMLREADER&
findsecbugsXXE_XMLREADERCRITICAL
R
"findsecbugs:ANDROID_WORLD_WRITABLE,
findsecbugsANDROID_WORLD_WRITABLEMAJOR
6
findsecbugs:ECB_MODE
findsecbugsECB_MODEMAJOR
J
findsecbugs:PREDICTABLE_RANDOM(
findsecbugsPREDICTABLE_RANDOMMAJOR
N
 findsecbugs:UNVALIDATED_REDIRECT*
findsecbugsUNVALIDATED_REDIRECTMAJOR
G
findsecbugs:XPATH_INJECTION(
findsecbugsXPATH_INJECTIONCRITICAL
A
findsecbugs:JAXRS_ENDPOINT#
findsecbugsJAXRS_ENDPOINTINFO
S
!findsecbugs:SQL_INJECTION_TURBINE.
findsecbugsSQL_INJECTION_TURBINECRITICAL
W
#findsecbugs:BEAN_PROPERTY_INJECTION0
findsecbugsBEAN_PROPERTY_INJECTIONCRITICAL
<
findsecbugs:SSL_CONTEXT!
findsecbugsSSL_CONTEXTMAJOR
I
findsecbugs:WEAK_FILENAMEUTILS'
findsecbugsWEAK_FILENAMEUTILSINFO
C
findsecbugs:ESAPI_ENCRYPTOR$
findsecbugsESAPI_ENCRYPTORINFO
M
 findsecbugs:SERVLET_QUERY_STRING)
findsecbugsSERVLET_QUERY_STRINGINFO
M
findsecbugs:SQL_INJECTION_JDBC+
findsecbugsSQL_INJECTION_JDBCCRITICAL
[
'findsecbugs:ANDROID_WEB_VIEW_JAVASCRIPT0
findsecbugsANDROID_WEB_VIEW_JAVASCRIPTINFO
A
findsecbugs:EL_INJECTION%
findsecbugsEL_INJECTIONCRITICAL
W
#findsecbugs:SCRIPT_ENGINE_INJECTION0
findsecbugsSCRIPT_ENGINE_INJECTIONCRITICAL
E
findsecbugs:MALICIOUS_XSLT'
findsecbugsMALICIOUS_XSLTCRITICAL
H
findsecbugs:PATH_TRAVERSAL_IN'
findsecbugsPATH_TRAVERSAL_INMAJOR
E
findsecbugs:STRUTS2_ENDPOINT%
findsecbugsSTRUTS2_ENDPOINTINFO
W
%findsecbugs:SERVLET_HEADER_USER_AGENT.
findsecbugsSERVLET_HEADER_USER_AGENTINFO
R
"findsecbugs:STRUTS_FILE_DISCLOSURE,
findsecbugsSTRUTS_FILE_DISCLOSUREMAJOR
C
findsecbugs:XXE_SAXPARSER&
findsecbugsXXE_SAXPARSERCRITICAL
W
#findsecbugs:SQL_INJECTION_HIBERNATE0
findsecbugsSQL_INJECTION_HIBERNATECRITICAL
O
findsecbugs:XXE_XMLSTREAMREADER,
findsecbugsXXE_XMLSTREAMREADERCRITICAL
L
findsecbugs:DEFAULT_HTTP_CLIENT)
findsecbugsDEFAULT_HTTP_CLIENTMAJOR
M
 findsecbugs:SERVLET_CONTENT_TYPE)
findsecbugsSERVLET_CONTENT_TYPEINFO
K
findsecbugs:SERVLET_SERVER_NAME(
findsecbugsSERVLET_SERVER_NAMEINFO
F
findsecbugs:CIPHER_INTEGRITY&
findsecbugsCIPHER_INTEGRITYMAJOR
b
*findsecbugs:HAZELCAST_SYMMETRIC_ENCRYPTION4
findsecbugsHAZELCAST_SYMMETRIC_ENCRYPTIONMAJOR
A
findsecbugs:JAXWS_ENDPOINT#
findsecbugsJAXWS_ENDPOINTINFO
H
findsecbugs:INSECURE_SMTP_SSL'
findsecbugsINSECURE_SMTP_SSLMAJOR
G
findsecbugs:SERVLET_PARAMETER&
findsecbugsSERVLET_PARAMETERINFO
K
findsecbugs:SQL_INJECTION_JDO*
findsecbugsSQL_INJECTION_JDOCRITICAL
_
'findsecbugs:TEMPLATE_INJECTION_VELOCITY4
findsecbugsTEMPLATE_INJECTION_VELOCITYCRITICAL
A
findsecbugs:XXE_DOCUMENT%
findsecbugsXXE_DOCUMENTCRITICAL
G
findsecbugs:ANDROID_BROADCAST&
findsecbugsANDROID_BROADCASTINFO
O
findsecbugs:AWS_QUERY_INJECTION,
findsecbugsAWS_QUERY_INJECTIONCRITICAL
B
findsecbugs:PADDING_ORACLE$
findsecbugsPADDING_ORACLEMAJOR
S
#findsecbugs:EXTERNAL_CONFIG_CONTROL,
findsecbugsEXTERNAL_CONFIG_CONTROLINFO
>
findsecbugs:RSA_KEY_SIZE"
findsecbugsRSA_KEY_SIZEMAJOR
E
findsecbugs:STRUTS1_ENDPOINT%
findsecbugsSTRUTS1_ENDPOINTINFO
=
findsecbugs:COOKIE_USAGE!
findsecbugsCOOKIE_USAGEINFO
E
findsecbugs:OGNL_INJECTION'
findsecbugsOGNL_INJECTIONCRITICAL
V
$findsecbugs:TRUST_BOUNDARY_VIOLATION.
findsecbugsTRUST_BOUNDARY_VIOLATIONMAJOR
^
(findsecbugs:ANDROID_EXTERNAL_FILE_ACCESS2
findsecbugsANDROID_EXTERNAL_FILE_ACCESSMAJOR
I
findsecbugs:SERVLET_SESSION_ID'
findsecbugsSERVLET_SESSION_IDINFO
R
"findsecbugs:WEAK_HOSTNAME_VERIFIER,
findsecbugsWEAK_HOSTNAME_VERIFIERMAJOR
V
$findsecbugs:HTTP_PARAMETER_POLLUTION.
findsecbugsHTTP_PARAMETER_POLLUTIONMAJOR
B
findsecbugs:LDAP_ANONYMOUS$
findsecbugsLDAP_ANONYMOUSMAJOR
d
+findsecbugs:SPRING_CSRF_PROTECTION_DISABLED5
findsecbugsSPRING_CSRF_PROTECTION_DISABLEDMAJOR
M
 findsecbugs:FILE_UPLOAD_FILENAME)
findsecbugsFILE_UPLOAD_FILENAMEINFO
D
findsecbugs:HTTPONLY_COOKIE%
findsecbugsHTTPONLY_COOKIEMAJOR
f
,findbugs:XSS_REQUEST_PARAMETER_TO_SEND_ERROR6
findbugs#XSS_REQUEST_PARAMETER_TO_SEND_ERRORMAJOR
^
(findbugs:HRS_REQUEST_PARAMETER_TO_COOKIE2
findbugsHRS_REQUEST_PARAMETER_TO_COOKIEMAJOR
P
!findbugs:DMI_CONSTANT_DB_PASSWORD+
findbugsDMI_CONSTANT_DB_PASSWORDMAJOR
h
-findbugs:HRS_REQUEST_PARAMETER_TO_HTTP_HEADER7
findbugs$HRS_REQUEST_PARAMETER_TO_HTTP_HEADERMAJOR
p
1findbugs:SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE;
findbugs(SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTEMAJOR
n
0findbugs:XSS_REQUEST_PARAMETER_TO_SERVLET_WRITER:
findbugs'XSS_REQUEST_PARAMETER_TO_SERVLET_WRITERMAJOR
J
findbugs:DMI_EMPTY_DB_PASSWORD(
findbugsDMI_EMPTY_DB_PASSWORDMAJOR
ê
Afindbugs:SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRINGK
findbugs8SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRINGMAJOR