
¯
squid:S1166Ÿ
squidS1166MAJOR"‡

exceptionsyjava.lang.InterruptedException, java.lang.NumberFormatException, java.text.ParseException, java.net.MalformedURLException
'
squid:S1221
squidS1221CRITICAL
$
squid:S1226
squidS1226MAJOR
;
squid:S1312,
squidS1312MAJOR"
formatLOG(?:GER)?
'
squid:S2095
squidS2095CRITICAL
O
squid:S00115?
squidS00115MAJOR"'
format^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$
$
squid:S1258
squidS1258MAJOR
E
squid:S001165
squidS00116MAJOR"
format^[a-z][a-zA-Z0-9]*$
E
squid:S001145
squidS00114MAJOR"
format^[A-Z][a-zA-Z0-9]*$
$
squid:S1134
squidS1134MAJOR
9
squid:S00119)
squidS00119MAJOR"
format^[A-Z]$
#
squid:S1133
squidS1133INFO
$
squid:S2221
squidS2221MAJOR
E
squid:S001175
squidS00117MAJOR"
format^[a-z][a-zA-Z0-9]*$
$
squid:S1132
squidS1132MAJOR
&
squid:S00122
squidS00122MAJOR
M
squid:S00120=
squidS00120MAJOR"%
format^[a-z]+(\.[a-z][a-z0-9]*)*$
'
squid:S1148
squidS1148CRITICAL
'
squid:S1147
squidS1147CRITICAL
$
squid:S2111
squidS2111MAJOR
&
squid:S00108
squidS00108MAJOR
&
squid:S1143
squidS1143BLOCKER
E
squid:S001075
squidS00107MAJOR"
max7"
constructorMax7
$
squid:S1141
squidS1141MAJOR
&
squid:S00112
squidS00112MAJOR
$
squid:S1149
squidS1149MAJOR
$
squid:S1596
squidS1596MAJOR
$
squid:S1118
squidS1118MAJOR
@
squid:UnusedPrivateMethod#
squidUnusedPrivateMethodMAJOR
>
squid:UselessImportCheck"
squidUselessImportCheckMINOR
H
squid:UselessParenthesesCheck'
squidUselessParenthesesCheckMAJOR
$
squid:S1126
squidS1126MAJOR
$
squid:S1125
squidS1125MINOR
$
squid:S1488
squidS1488MINOR
$
squid:S1175
squidS1175MAJOR
X
squid:ClassCyclomaticComplexity5
squidClassCyclomaticComplexityMAJOR"

max200
$
squid:S1174
squidS1174MAJOR
$
squid:S1170
squidS1170MAJOR
$
squid:S1171
squidS1171MAJOR
$
squid:S1068
squidS1068MAJOR
/
squid:S1188 
squidS1188MAJOR"	
Max20
.
squid:S1067
squidS1067MAJOR"
max3
$
squid:S1066
squidS1066MAJOR
$
squid:S1186
squidS1186MAJOR
$
squid:S1185
squidS1185MINOR
$
squid:S1182
squidS1182MAJOR
&
squid:S1181
squidS1181BLOCKER
$
squid:S1158
squidS1158MAJOR
$
squid:S1157
squidS1157MAJOR
N
 squid:LabelsShouldNotBeUsedCheck*
squidLabelsShouldNotBeUsedCheckMAJOR
$
squid:S1155
squidS1155MAJOR
.
squid:S1151
squidS1151MAJOR"
max5
$
squid:S1153
squidS1153MINOR
E
squid:S001005
squidS00100MAJOR"
format^[a-z][a-zA-Z0-9]*$
E
squid:S001015
squidS00101MAJOR"
format^[A-Z][a-zA-Z0-9]*$
$
squid:S1150
squidS1150MAJOR
$
squid:S1168
squidS1168MAJOR
$
squid:S1165
squidS1165MAJOR
$
squid:S1163
squidS1163MAJOR
$
squid:S1160
squidS1160MAJOR
V
$squid:AssignmentInSubExpressionCheck.
squidAssignmentInSubExpressionCheckMAJOR
C
squid:ObjectFinalizeCheck&
squidObjectFinalizeCheckCRITICAL
$
squid:S1301
squidS1301MINOR
B
squid:CommentedOutCodeLine$
squidCommentedOutCodeLineMAJOR
x
4squid:ObjectFinalizeOverridenCallsSuperFinalizeCheck@
squid.ObjectFinalizeOverridenCallsSuperFinalizeCheckBLOCKER
$
squid:S1213
squidS1213MINOR
$
squid:S1214
squidS1214MINOR
$
squid:S1696
squidS1696MAJOR
$
squid:S1452
squidS1452MAJOR
$
squid:S1694
squidS1694MAJOR
'
squid:S1210
squidS1210CRITICAL
'
squid:S1219
squidS1219CRITICAL
'
squid:S1217
squidS1217CRITICAL
'
squid:S1215
squidS1215CRITICAL
$
squid:S1223
squidS1223MAJOR
$
squid:S1220
squidS1220MAJOR
N
 squid:ForLoopCounterChangedCheck*
squidForLoopCounterChangedCheckMAJOR
U
"squid:ObjectFinalizeOverridenCheck/
squidObjectFinalizeOverridenCheckCRITICAL
$
squid:S1313
squidS1313MAJOR
$
squid:S1317
squidS1317MAJOR
$
squid:S1319
squidS1319MAJOR
$
squid:S1314
squidS1314MAJOR
'
squid:S1201
squidS1201CRITICAL
$
squid:S1444
squidS1444MAJOR
&
squid:S1206
squidS1206BLOCKER
T
#squid:RightCurlyBraceStartLineCheck-
squidRightCurlyBraceStartLineCheckMINOR
h
-squid:RightCurlyBraceSameLineAsNextBlockCheck7
squid'RightCurlyBraceSameLineAsNextBlockCheckMINOR
R
"squid:SwitchLastCaseIsDefaultCheck,
squidSwitchLastCaseIsDefaultCheckMAJOR
$
squid:S1611
squidS1611MINOR
:
squid:HiddenFieldCheck 
squidHiddenFieldCheckMAJOR
,

squid:S134
squidS134MINOR"
max5
_
 squid:MethodCyclomaticComplexity;
squidMethodCyclomaticComplexityMAJOR"
	Threshold10
%

squid:S128
squidS128CRITICAL
F
squid:MissingDeprecatedCheck&
squidMissingDeprecatedCheckMAJOR
$
squid:S1602
squidS1602MAJOR
"

squid:S135
squidS135MAJOR
"

squid:S106
squidS106MAJOR
J
squid:EmptyStatementUsageCheck(
squidEmptyStatementUsageCheckMAJOR
$
squid:S1199
squidS1199MAJOR
$
squid:S1197
squidS1197MINOR
$
squid:S1195
squidS1195MINOR
$
squid:S1194
squidS1194MAJOR
$
squid:S1190
squidS1190MAJOR
$
squid:S1191
squidS1191MAJOR
4
squid:S1192%
squidS1192MINOR"
	threshold5
$
squid:S1193
squidS1193MAJOR
R
"squid:ClassVariableVisibilityCheck,
squidClassVariableVisibilityCheckMAJOR
X
%squid:RedundantThrowsDeclarationCheck/
squidRedundantThrowsDeclarationCheckMINOR
@
squid:ModifiersOrderCheck#
squidModifiersOrderCheckMINOR
’
Bfindbugs:DMI_SCHEDULED_THREAD_POOL_EXECUTOR_WITH_ZERO_CORE_THREADSL
findbugs9DMI_SCHEDULED_THREAD_POOL_EXECUTOR_WITH_ZERO_CORE_THREADSMINOR
]
&findbugs:IM_MULTIPLYING_RESULT_OF_IREM3
findbugsIM_MULTIPLYING_RESULT_OF_IREMCRITICAL
u
2findbugs:ODR_OPEN_DATABASE_RESOURCE_EXCEPTION_PATH?
findbugs)ODR_OPEN_DATABASE_RESOURCE_EXCEPTION_PATHCRITICAL
W
#findbugs:LI_LAZY_INIT_UPDATE_STATIC0
findbugsLI_LAZY_INIT_UPDATE_STATICCRITICAL
y
4findbugs:WL_USING_GETCLASS_RATHER_THAN_CLASS_LITERALA
findbugs+WL_USING_GETCLASS_RATHER_THAN_CLASS_LITERALCRITICAL
¶
Tfindbugs:DMI_FUTILE_ATTEMPT_TO_CHANGE_MAXPOOL_SIZE_OF_SCHEDULED_THREAD_POOL_EXECUTOR^
findbugsKDMI_FUTILE_ATTEMPT_TO_CHANGE_MAXPOOL_SIZE_OF_SCHEDULED_THREAD_POOL_EXECUTORMINOR
K
findbugs:IJU_BAD_SUITE_METHOD*
findbugsIJU_BAD_SUITE_METHODCRITICAL
_
'findbugs:NS_DANGEROUS_NON_SHORT_CIRCUIT4
findbugsNS_DANGEROUS_NON_SHORT_CIRCUITCRITICAL
`
)findbugs:RV_DONT_JUST_NULL_CHECK_READLINE3
findbugs RV_DONT_JUST_NULL_CHECK_READLINEMAJOR
S
!findbugs:SA_LOCAL_SELF_ASSIGNMENT.
findbugsSA_LOCAL_SELF_ASSIGNMENTCRITICAL
1
findbugs:BIT_AND
findbugsBIT_ANDCRITICAL
ƒ
9findbugs:RE_CANT_USE_FILE_SEPARATOR_AS_REGULAR_EXPRESSIONF
findbugs0RE_CANT_USE_FILE_SEPARATOR_AS_REGULAR_EXPRESSIONCRITICAL
?
findbugs:DM_NUMBER_CTOR$
findbugsDM_NUMBER_CTORCRITICAL
R
"findbugs:FI_FINALIZER_NULLS_FIELDS,
findbugsFI_FINALIZER_NULLS_FIELDSMAJOR
B
findbugs:MS_OOI_PKGPROTECT$
findbugsMS_OOI_PKGPROTECTMAJOR
_
'findbugs:STCAL_STATIC_CALENDAR_INSTANCE4
findbugsSTCAL_STATIC_CALENDAR_INSTANCECRITICAL
I
findbugs:BC_UNCONFIRMED_CAST)
findbugsBC_UNCONFIRMED_CASTCRITICAL
s
1findbugs:RCN_REDUNDANT_COMPARISON_TWO_NULL_VALUES>
findbugs(RCN_REDUNDANT_COMPARISON_TWO_NULL_VALUESCRITICAL
m
.findbugs:RCN_REDUNDANT_NULLCHECK_OF_NULL_VALUE;
findbugs%RCN_REDUNDANT_NULLCHECK_OF_NULL_VALUECRITICAL
L
findbugs:DMI_UNSUPPORTED_METHOD)
findbugsDMI_UNSUPPORTED_METHODMAJOR
8
findbugs:NM_CONFUSING
findbugsNM_CONFUSINGMAJOR
u
2findbugs:NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS?
findbugs)NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUSCRITICAL
Š
>findbugs:TQ_COMPARING_VALUES_WITH_INCOMPATIBLE_TYPE_QUALIFIERSH
findbugs5TQ_COMPARING_VALUES_WITH_INCOMPATIBLE_TYPE_QUALIFIERSMAJOR
J
findbugs:MF_METHOD_MASKS_FIELD(
findbugsMF_METHOD_MASKS_FIELDMAJOR
‰
<findbugs:NP_PARAMETER_MUST_BE_NONNULL_BUT_MARKED_AS_NULLABLEI
findbugs3NP_PARAMETER_MUST_BE_NONNULL_BUT_MARKED_AS_NULLABLECRITICAL
@
findbugs:NM_WRONG_PACKAGE#
findbugsNM_WRONG_PACKAGEMAJOR
c
)findbugs:STI_INTERRUPTED_ON_CURRENTTHREAD6
findbugs STI_INTERRUPTED_ON_CURRENTTHREADCRITICAL
g
-findbugs:UUF_UNUSED_PUBLIC_OR_PROTECTED_FIELD6
findbugs$UUF_UNUSED_PUBLIC_OR_PROTECTED_FIELDINFO
a
(findbugs:HSC_HUGE_SHARED_STRING_CONSTANT5
findbugsHSC_HUGE_SHARED_STRING_CONSTANTCRITICAL
q
0findbugs:SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH=
findbugs'SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGHCRITICAL
]
&findbugs:FL_MATH_USING_FLOAT_PRECISION3
findbugsFL_MATH_USING_FLOAT_PRECISIONCRITICAL
V
$findbugs:ICAST_INT_2_LONG_AS_INSTANT.
findbugsICAST_INT_2_LONG_AS_INSTANTMAJOR
x
5findbugs:UR_UNINIT_READ_CALLED_FROM_SUPER_CONSTRUCTOR?
findbugs,UR_UNINIT_READ_CALLED_FROM_SUPER_CONSTRUCTORMAJOR
}
6findbugs:RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPEC
findbugs-RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPECRITICAL
>
findbugs:DE_MIGHT_IGNORE"
findbugsDE_MIGHT_IGNOREMAJOR
R
"findbugs:DM_RUN_FINALIZERS_ON_EXIT,
findbugsDM_RUN_FINALIZERS_ON_EXITMAJOR
u
2findbugs:IJU_ASSERT_METHOD_INVOKED_FROM_RUN_METHOD?
findbugs)IJU_ASSERT_METHOD_INVOKED_FROM_RUN_METHODCRITICAL
i
,findbugs:INT_BAD_COMPARISON_WITH_SIGNED_BYTE9
findbugs#INT_BAD_COMPARISON_WITH_SIGNED_BYTECRITICAL
S
!findbugs:NP_ALWAYS_NULL_EXCEPTION.
findbugsNP_ALWAYS_NULL_EXCEPTIONCRITICAL
W
#findbugs:SA_FIELD_DOUBLE_ASSIGNMENT0
findbugsSA_FIELD_DOUBLE_ASSIGNMENTCRITICAL
_
'findbugs:DLS_DEAD_LOCAL_STORE_IN_RETURN4
findbugsDLS_DEAD_LOCAL_STORE_IN_RETURNCRITICAL
S
!findbugs:SWL_SLEEP_WITH_LOCK_HELD.
findbugsSWL_SLEEP_WITH_LOCK_HELDCRITICAL
N
findbugs:BC_IMPOSSIBLE_DOWNCAST+
findbugsBC_IMPOSSIBLE_DOWNCASTBLOCKER
e
*findbugs:GC_UNCHECKED_TYPE_IN_GENERIC_CALL7
findbugs!GC_UNCHECKED_TYPE_IN_GENERIC_CALLCRITICAL
k
-findbugs:IO_APPENDING_TO_OBJECT_OUTPUT_STREAM:
findbugs$IO_APPENDING_TO_OBJECT_OUTPUT_STREAMCRITICAL
D
findbugs:MS_CANNOT_BE_FINAL%
findbugsMS_CANNOT_BE_FINALMAJOR
R
"findbugs:NP_ARGUMENT_MIGHT_BE_NULL,
findbugsNP_ARGUMENT_MIGHT_BE_NULLMAJOR
Y
$findbugs:SE_NONFINAL_SERIALVERSIONID1
findbugsSE_NONFINAL_SERIALVERSIONIDCRITICAL
S
!findbugs:QF_QUESTIONABLE_FOR_LOOP.
findbugsQF_QUESTIONABLE_FOR_LOOPCRITICAL
m
.findbugs:DL_SYNCHRONIZATION_ON_BOXED_PRIMITIVE;
findbugs%DL_SYNCHRONIZATION_ON_BOXED_PRIMITIVECRITICAL
C
findbugs:DM_STRING_TOSTRING$
findbugsDM_STRING_TOSTRINGINFO
E
findbugs:RC_REF_COMPARISON'
findbugsRC_REF_COMPARISONCRITICAL
7
findbugs:BIT_AND_ZZ 
findbugs
BIT_AND_ZZCRITICAL
V
$findbugs:DM_BOXED_PRIMITIVE_TOSTRING.
findbugsDM_BOXED_PRIMITIVE_TOSTRINGMAJOR
j
.findbugs:SIC_INNER_SHOULD_BE_STATIC_NEEDS_THIS8
findbugs%SIC_INNER_SHOULD_BE_STATIC_NEEDS_THISMAJOR
_
'findbugs:EQ_GETCLASS_AND_CLASS_CONSTANT4
findbugsEQ_GETCLASS_AND_CLASS_CONSTANTCRITICAL
Y
$findbugs:NP_NONNULL_RETURN_VIOLATION1
findbugsNP_NONNULL_RETURN_VIOLATIONCRITICAL
]
&findbugs:NP_TOSTRING_COULD_RETURN_NULL3
findbugsNP_TOSTRING_COULD_RETURN_NULLCRITICAL
U
"findbugs:ICAST_IDIV_CAST_TO_DOUBLE/
findbugsICAST_IDIV_CAST_TO_DOUBLECRITICAL
`
)findbugs:NM_SAME_SIMPLE_NAME_AS_INTERFACE3
findbugs NM_SAME_SIMPLE_NAME_AS_INTERFACEMAJOR
G
findbugs:SE_BAD_FIELD_STORE(
findbugsSE_BAD_FIELD_STORECRITICAL
\
&findbugs:EC_INCOMPATIBLE_ARRAY_COMPARE2
findbugsEC_INCOMPATIBLE_ARRAY_COMPAREBLOCKER
ˆ
=findbugs:IA_AMBIGUOUS_INVOCATION_OF_INHERITED_OR_OUTER_METHODG
findbugs4IA_AMBIGUOUS_INVOCATION_OF_INHERITED_OR_OUTER_METHODMAJOR
]
&findbugs:OS_OPEN_STREAM_EXCEPTION_PATH3
findbugsOS_OPEN_STREAM_EXCEPTION_PATHCRITICAL
‰
<findbugs:TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_NEVER_SINKI
findbugs3TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_NEVER_SINKCRITICAL
U
"findbugs:DLS_OVERWRITTEN_INCREMENT/
findbugsDLS_OVERWRITTEN_INCREMENTCRITICAL
>
findbugs:EQ_ALWAYS_TRUE#
findbugsEQ_ALWAYS_TRUEBLOCKER

8findbugs:NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTORE
findbugs/NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTORCRITICAL
F
findbugs:NP_NULL_INSTANCEOF'
findbugsNP_NULL_INSTANCEOFBLOCKER
B
findbugs:DM_USELESS_THREAD$
findbugsDM_USELESS_THREADMAJOR
c
)findbugs:EC_UNRELATED_CLASS_AND_INTERFACE6
findbugs EC_UNRELATED_CLASS_AND_INTERFACECRITICAL
J
findbugs:FI_MISSING_SUPER_CALL(
findbugsFI_MISSING_SUPER_CALLMAJOR
K
findbugs:EC_BAD_ARRAY_COMPARE*
findbugsEC_BAD_ARRAY_COMPARECRITICAL
@
findbugs:CO_ABSTRACT_SELF#
findbugsCO_ABSTRACT_SELFMAJOR
M
findbugs:EC_ARRAY_AND_NONARRAY+
findbugsEC_ARRAY_AND_NONARRAYCRITICAL
a
(findbugs:HE_INHERITS_EQUALS_USE_HASHCODE5
findbugsHE_INHERITS_EQUALS_USE_HASHCODECRITICAL
W
#findbugs:NP_CLONE_COULD_RETURN_NULL0
findbugsNP_CLONE_COULD_RETURN_NULLCRITICAL
T
#findbugs:SE_NONLONG_SERIALVERSIONID-
findbugsSE_NONLONG_SERIALVERSIONIDMAJOR
S
!findbugs:SQL_BAD_RESULTSET_ACCESS.
findbugsSQL_BAD_RESULTSET_ACCESSCRITICAL
A
findbugs:NN_NAKED_NOTIFY%
findbugsNN_NAKED_NOTIFYCRITICAL
h
-findbugs:SE_COMPARATOR_SHOULD_BE_SERIALIZABLE7
findbugs$SE_COMPARATOR_SHOULD_BE_SERIALIZABLEMAJOR
S
!findbugs:UCF_USELESS_CONTROL_FLOW.
findbugsUCF_USELESS_CONTROL_FLOWCRITICAL
N
findbugs:DMI_COLLECTION_OF_URLS+
findbugsDMI_COLLECTION_OF_URLSBLOCKER
w
3findbugs:VA_PRIMITIVE_ARRAY_PASSED_TO_OBJECT_VARARG@
findbugs*VA_PRIMITIVE_ARRAY_PASSED_TO_OBJECT_VARARGCRITICAL
p
1findbugs:SW_SWING_METHODS_INVOKED_IN_SWING_THREAD;
findbugs(SW_SWING_METHODS_INVOKED_IN_SWING_THREADMAJOR
s
1findbugs:STCAL_INVOKE_ON_STATIC_CALENDAR_INSTANCE>
findbugs(STCAL_INVOKE_ON_STATIC_CALENDAR_INSTANCECRITICAL
j
.findbugs:CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE8
findbugs%CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLEMAJOR
K
findbugs:IJU_SUITE_NOT_STATIC*
findbugsIJU_SUITE_NOT_STATICCRITICAL
U
"findbugs:BIT_SIGNED_CHECK_HIGH_BIT/
findbugsBIT_SIGNED_CHECK_HIGH_BITCRITICAL
C
findbugs:INT_BAD_REM_BY_1&
findbugsINT_BAD_REM_BY_1CRITICAL
Z
&findbugs:RpC_REPEATED_CONDITIONAL_TEST0
findbugsRpC_REPEATED_CONDITIONAL_TESTMAJOR
‚
:findbugs:BX_BOXING_IMMEDIATELY_UNBOXED_TO_PERFORM_COERCIOND
findbugs1BX_BOXING_IMMEDIATELY_UNBOXED_TO_PERFORM_COERCIONMAJOR
l
/findbugs:DMI_BIGDECIMAL_CONSTRUCTED_FROM_DOUBLE9
findbugs&DMI_BIGDECIMAL_CONSTRUCTED_FROM_DOUBLEMAJOR
T
#findbugs:DP_DO_INSIDE_DO_PRIVILEGED-
findbugsDP_DO_INSIDE_DO_PRIVILEGEDMAJOR
[
%findbugs:JLM_JSR166_LOCK_MONITORENTER2
findbugsJLM_JSR166_LOCK_MONITORENTERCRITICAL
T
#findbugs:PT_RELATIVE_PATH_TRAVERSAL-
findbugsPT_RELATIVE_PATH_TRAVERSALMAJOR
B
findbugs:TLW_TWO_LOCK_WAIT$
findbugsTLW_TWO_LOCK_WAITMAJOR
K
findbugs:IS_FIELD_NOT_GUARDED*
findbugsIS_FIELD_NOT_GUARDEDCRITICAL
F
findbugs:MS_FINAL_PKGPROTECT&
findbugsMS_FINAL_PKGPROTECTMAJOR
8
findbugs:SE_BAD_FIELD
findbugsSE_BAD_FIELDMAJOR
i
,findbugs:BC_UNCONFIRMED_CAST_OF_RETURN_VALUE9
findbugs#BC_UNCONFIRMED_CAST_OF_RETURN_VALUECRITICAL
g
+findbugs:SI_INSTANCE_BEFORE_FINALS_ASSIGNED8
findbugs"SI_INSTANCE_BEFORE_FINALS_ASSIGNEDCRITICAL
[
%findbugs:BOA_BADLY_OVERRIDDEN_ADAPTER2
findbugsBOA_BADLY_OVERRIDDEN_ADAPTERCRITICAL
Z
&findbugs:BX_BOXING_IMMEDIATELY_UNBOXED0
findbugsBX_BOXING_IMMEDIATELY_UNBOXEDMAJOR
c
)findbugs:DMI_VACUOUS_SELF_COLLECTION_CALL6
findbugs DMI_VACUOUS_SELF_COLLECTION_CALLCRITICAL
b
*findbugs:UI_INHERITANCE_UNSAFE_GETRESOURCE4
findbugs!UI_INHERITANCE_UNSAFE_GETRESOURCEMAJOR
_
'findbugs:NP_NULL_PARAM_DEREF_NONVIRTUAL4
findbugsNP_NULL_PARAM_DEREF_NONVIRTUALCRITICAL
x
5findbugs:RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUE?
findbugs,RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUEMAJOR

7findbugs:DL_SYNCHRONIZATION_ON_UNSHARED_BOXED_PRIMITIVED
findbugs.DL_SYNCHRONIZATION_ON_UNSHARED_BOXED_PRIMITIVECRITICAL
o
/findbugs:DMI_LONG_BITS_TO_DOUBLE_INVOKED_ON_INT<
findbugs&DMI_LONG_BITS_TO_DOUBLE_INVOKED_ON_INTCRITICAL
P
!findbugs:EQ_COMPARING_CLASS_NAMES+
findbugsEQ_COMPARING_CLASS_NAMESMAJOR
s
1findbugs:DMI_INVOKING_TOSTRING_ON_ANONYMOUS_ARRAY>
findbugs(DMI_INVOKING_TOSTRING_ON_ANONYMOUS_ARRAYCRITICAL
@
findbugs:NP_CLOSING_NULL$
findbugsNP_CLOSING_NULLBLOCKER
u
2findbugs:TQ_MAYBE_SOURCE_VALUE_REACHES_ALWAYS_SINK?
findbugs)TQ_MAYBE_SOURCE_VALUE_REACHES_ALWAYS_SINKCRITICAL
J
findbugs:EI_EXPOSE_STATIC_REP2(
findbugsEI_EXPOSE_STATIC_REP2MAJOR
K
findbugs:PS_PUBLIC_SEMAPHORES*
findbugsPS_PUBLIC_SEMAPHORESCRITICAL
F
findbugs:BC_IMPOSSIBLE_CAST'
findbugsBC_IMPOSSIBLE_CASTBLOCKER
P
!findbugs:ML_SYNC_ON_UPDATED_FIELD+
findbugsML_SYNC_ON_UPDATED_FIELDMAJOR
q
0findbugs:ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD=
findbugs'ST_WRITE_TO_STATIC_FROM_INSTANCE_METHODCRITICAL
@
findbugs:UUF_UNUSED_FIELD#
findbugsUUF_UNUSED_FIELDMAJOR
=
findbugs:MS_EXPOSE_REP#
findbugsMS_EXPOSE_REPCRITICAL
;
findbugs:NM_BAD_EQUAL"
findbugsNM_BAD_EQUALCRITICAL
o
/findbugs:NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE<
findbugs&NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUECRITICAL
l
/findbugs:RC_REF_COMPARISON_BAD_PRACTICE_BOOLEAN9
findbugs&RC_REF_COMPARISON_BAD_PRACTICE_BOOLEANMAJOR
K
findbugs:RV_REM_OF_RANDOM_INT*
findbugsRV_REM_OF_RANDOM_INTCRITICAL
i
,findbugs:XSS_REQUEST_PARAMETER_TO_SEND_ERROR9
findbugs#XSS_REQUEST_PARAMETER_TO_SEND_ERRORCRITICAL
g
+findbugs:DMI_NONSERIALIZABLE_OBJECT_WRITTEN8
findbugs"DMI_NONSERIALIZABLE_OBJECT_WRITTENCRITICAL
^
(findbugs:NM_METHOD_CONSTRUCTOR_CONFUSION2
findbugsNM_METHOD_CONSTRUCTOR_CONFUSIONMAJOR
^
(findbugs:AM_CREATES_EMPTY_ZIP_FILE_ENTRY2
findbugsAM_CREATES_EMPTY_ZIP_FILE_ENTRYMAJOR
C
findbugs:BIT_SIGNED_CHECK&
findbugsBIT_SIGNED_CHECKCRITICAL
H
findbugs:NS_NON_SHORT_CIRCUIT'
findbugsNS_NON_SHORT_CIRCUITMAJOR
M
findbugs:DB_DUPLICATE_BRANCHES+
findbugsDB_DUPLICATE_BRANCHESCRITICAL
a
(findbugs:DMI_HARDCODED_ABSOLUTE_FILENAME5
findbugsDMI_HARDCODED_ABSOLUTE_FILENAMECRITICAL
F
findbugs:UWF_UNWRITTEN_FIELD&
findbugsUWF_UNWRITTEN_FIELDMINOR
F
findbugs:DM_NEW_FOR_GETCLASS&
findbugsDM_NEW_FOR_GETCLASSMAJOR
\
'findbugs:SIC_THREADLOCAL_DEADLY_EMBRACE1
findbugsSIC_THREADLOCAL_DEADLY_EMBRACEMAJOR
a
(findbugs:VA_FORMAT_STRING_BAD_CONVERSION5
findbugsVA_FORMAT_STRING_BAD_CONVERSIONCRITICAL
t
3findbugs:VA_FORMAT_STRING_BAD_CONVERSION_FROM_ARRAY=
findbugs*VA_FORMAT_STRING_BAD_CONVERSION_FROM_ARRAYMAJOR
F
findbugs:DM_DEFAULT_ENCODING&
findbugsDM_DEFAULT_ENCODINGMAJOR
g
-findbugs:URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD6
findbugs$URF_UNREAD_PUBLIC_OR_PROTECTED_FIELDINFO
?
findbugs:UWF_NULL_FIELD$
findbugsUWF_NULL_FIELDCRITICAL
W
#findbugs:FE_FLOATING_POINT_EQUALITY0
findbugsFE_FLOATING_POINT_EQUALITYCRITICAL
U
"findbugs:INT_VACUOUS_BIT_OPERATION/
findbugsINT_VACUOUS_BIT_OPERATIONCRITICAL
e
*findbugs:UL_UNRELEASED_LOCK_EXCEPTION_PATH7
findbugs!UL_UNRELEASED_LOCK_EXCEPTION_PATHCRITICAL
R
"findbugs:MSF_MUTABLE_SERVLET_FIELD,
findbugsMSF_MUTABLE_SERVLET_FIELDMAJOR
X
%findbugs:NM_WRONG_PACKAGE_INTENTIONAL/
findbugsNM_WRONG_PACKAGE_INTENTIONALMAJOR
s
1findbugs:NP_NULL_ON_SOME_PATH_MIGHT_BE_INFEASIBLE>
findbugs(NP_NULL_ON_SOME_PATH_MIGHT_BE_INFEASIBLECRITICAL
^
(findbugs:HRS_REQUEST_PARAMETER_TO_COOKIE2
findbugsHRS_REQUEST_PARAMETER_TO_COOKIEMAJOR
b
*findbugs:NM_SAME_SIMPLE_NAME_AS_SUPERCLASS4
findbugs!NM_SAME_SIMPLE_NAME_AS_SUPERCLASSMAJOR
m
.findbugs:NP_GUARANTEED_DEREF_ON_EXCEPTION_PATH;
findbugs%NP_GUARANTEED_DEREF_ON_EXCEPTION_PATHCRITICAL
t
3findbugs:VA_FORMAT_STRING_BAD_CONVERSION_TO_BOOLEAN=
findbugs*VA_FORMAT_STRING_BAD_CONVERSION_TO_BOOLEANMAJOR
e
*findbugs:SQL_BAD_PREPARED_STATEMENT_ACCESS7
findbugs!SQL_BAD_PREPARED_STATEMENT_ACCESSCRITICAL
G
findbugs:RS_READOBJECT_SYNC(
findbugsRS_READOBJECT_SYNCCRITICAL
N
 findbugs:RV_RETURN_VALUE_IGNORED*
findbugsRV_RETURN_VALUE_IGNOREDMINOR
u
2findbugs:UMAC_UNCALLABLE_METHOD_OF_ANONYMOUS_CLASS?
findbugs)UMAC_UNCALLABLE_METHOD_OF_ANONYMOUS_CLASSCRITICAL
4
findbugs:FI_USELESS
findbugs
FI_USELESSMINOR
<
findbugs:RR_NOT_CHECKED!
findbugsRR_NOT_CHECKEDMAJOR
<
findbugs:SR_NOT_CHECKED!
findbugsSR_NOT_CHECKEDMAJOR
\
'findbugs:CO_COMPARETO_RESULTS_MIN_VALUE1
findbugsCO_COMPARETO_RESULTS_MIN_VALUEMAJOR
u
2findbugs:EC_UNRELATED_TYPES_USING_POINTER_EQUALITY?
findbugs)EC_UNRELATED_TYPES_USING_POINTER_EQUALITYCRITICAL
D
findbugs:NP_UNWRITTEN_FIELD%
findbugsNP_UNWRITTEN_FIELDMAJOR
R
"findbugs:DMI_ARGUMENTS_WRONG_ORDER,
findbugsDMI_ARGUMENTS_WRONG_ORDERMINOR
R
!findbugs:DMI_CONSTANT_DB_PASSWORD-
findbugsDMI_CONSTANT_DB_PASSWORDBLOCKER
F
findbugs:DM_STRING_VOID_CTOR&
findbugsDM_STRING_VOID_CTORMAJOR
h
-findbugs:HRS_REQUEST_PARAMETER_TO_HTTP_HEADER7
findbugs$HRS_REQUEST_PARAMETER_TO_HTTP_HEADERMAJOR
m
.findbugs:NP_EQUALS_SHOULD_HANDLE_NULL_ARGUMENT;
findbugs%NP_EQUALS_SHOULD_HANDLE_NULL_ARGUMENTCRITICAL
^
(findbugs:SIC_INNER_SHOULD_BE_STATIC_ANON2
findbugsSIC_INNER_SHOULD_BE_STATIC_ANONMAJOR
O
findbugs:XFB_XML_FACTORY_BYPASS,
findbugsXFB_XML_FACTORY_BYPASSCRITICAL
t
3findbugs:DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED=
findbugs*DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGEDMAJOR
g
+findbugs:UCF_USELESS_CONTROL_FLOW_NEXT_LINE8
findbugs"UCF_USELESS_CONTROL_FLOW_NEXT_LINECRITICAL
T
#findbugs:PT_ABSOLUTE_PATH_TRAVERSAL-
findbugsPT_ABSOLUTE_PATH_TRAVERSALMAJOR
F
findbugs:REC_CATCH_EXCEPTION&
findbugsREC_CATCH_EXCEPTIONMAJOR
p
1findbugs:JCIP_FIELD_ISNT_FINAL_IN_IMMUTABLE_CLASS;
findbugs(JCIP_FIELD_ISNT_FINAL_IN_IMMUTABLE_CLASSMINOR
u
2findbugs:TQ_ALWAYS_VALUE_USED_WHERE_NEVER_REQUIRED?
findbugs)TQ_ALWAYS_VALUE_USED_WHERE_NEVER_REQUIREDCRITICAL
q
0findbugs:ICAST_INT_CAST_TO_DOUBLE_PASSED_TO_CEIL=
findbugs'ICAST_INT_CAST_TO_DOUBLE_PASSED_TO_CEILCRITICAL
M
findbugs:IS2_INCONSISTENT_SYNC+
findbugsIS2_INCONSISTENT_SYNCCRITICAL
J
findbugs:SE_NO_SERIALVERSIONID(
findbugsSE_NO_SERIALVERSIONIDMAJOR
0
findbugs:FI_EMPTY
findbugsFI_EMPTYMAJOR
H
findbugs:MS_MUTABLE_HASHTABLE'
findbugsMS_MUTABLE_HASHTABLEMAJOR
c
)findbugs:STI_INTERRUPTED_ON_UNKNOWNTHREAD6
findbugs STI_INTERRUPTED_ON_UNKNOWNTHREADCRITICAL
v
4findbugs:NM_FUTURE_KEYWORD_USED_AS_MEMBER_IDENTIFIER>
findbugs+NM_FUTURE_KEYWORD_USED_AS_MEMBER_IDENTIFIERMAJOR
U
"findbugs:SA_LOCAL_SELF_COMPUTATION/
findbugsSA_LOCAL_SELF_COMPUTATIONCRITICAL
R
"findbugs:SE_METHOD_MUST_BE_PRIVATE,
findbugsSE_METHOD_MUST_BE_PRIVATEMAJOR
?
findbugs:WA_NOT_IN_LOOP$
findbugsWA_NOT_IN_LOOPCRITICAL
k
-findbugs:IP_PARAMETER_IS_DEAD_BUT_OVERWRITTEN:
findbugs$IP_PARAMETER_IS_DEAD_BUT_OVERWRITTENCRITICAL
ƒ
9findbugs:SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH_TO_THROWF
findbugs0SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH_TO_THROWCRITICAL
L
findbugs:UG_SYNC_SET_UNSYNC_GET)
findbugsUG_SYNC_SET_UNSYNC_GETMAJOR
\
'findbugs:FI_FINALIZER_ONLY_NULLS_FIELDS1
findbugsFI_FINALIZER_ONLY_NULLS_FIELDSMAJOR
|
7findbugs:SE_NO_SUITABLE_CONSTRUCTOR_FOR_EXTERNALIZATIONA
findbugs.SE_NO_SUITABLE_CONSTRUCTOR_FOR_EXTERNALIZATIONMAJOR
N
 findbugs:CI_CONFUSED_INHERITANCE*
findbugsCI_CONFUSED_INHERITANCEMINOR
B
findbugs:NM_LCASE_TOSTRING$
findbugsNM_LCASE_TOSTRINGMAJOR
Z
&findbugs:NM_VERY_CONFUSING_INTENTIONAL0
findbugsNM_VERY_CONFUSING_INTENTIONALMAJOR
U
"findbugs:DMI_RANDOM_USED_ONLY_ONCE/
findbugsDMI_RANDOM_USED_ONLY_ONCECRITICAL
r
2findbugs:DMI_THREAD_PASSED_WHERE_RUNNABLE_EXPECTED<
findbugs)DMI_THREAD_PASSED_WHERE_RUNNABLE_EXPECTEDMAJOR
I
findbugs:NP_NULL_PARAM_DEREF)
findbugsNP_NULL_PARAM_DEREFCRITICAL
_
'findbugs:RE_POSSIBLE_UNINTENDED_PATTERN4
findbugsRE_POSSIBLE_UNINTENDED_PATTERNCRITICAL
O
findbugs:BIT_IOR_OF_SIGNED_BYTE,
findbugsBIT_IOR_OF_SIGNED_BYTECRITICAL
:
findbugs:EI_EXPOSE_REP 
findbugsEI_EXPOSE_REPMAJOR
@
findbugs:EQ_ALWAYS_FALSE$
findbugsEQ_ALWAYS_FALSEBLOCKER
<
findbugs:DC_DOUBLECHECK!
findbugsDC_DOUBLECHECKMAJOR
X
%findbugs:DM_MONITOR_WAIT_ON_CONDITION/
findbugsDM_MONITOR_WAIT_ON_CONDITIONMAJOR
=
findbugs:DMI_BAD_MONTH#
findbugsDMI_BAD_MONTHCRITICAL
K
findbugs:IM_BAD_CHECK_FOR_ODD*
findbugsIM_BAD_CHECK_FOR_ODDCRITICAL
d
+findbugs:DLS_DEAD_LOCAL_STORE_SHADOWS_FIELD5
findbugs"DLS_DEAD_LOCAL_STORE_SHADOWS_FIELDMAJOR
l
/findbugs:DMI_ENTRY_SETS_MAY_REUSE_ENTRY_OBJECTS9
findbugs&DMI_ENTRY_SETS_MAY_REUSE_ENTRY_OBJECTSMAJOR
W
#findbugs:IL_INFINITE_RECURSIVE_LOOP0
findbugsIL_INFINITE_RECURSIVE_LOOPCRITICAL
c
)findbugs:NP_DEREFERENCE_OF_READLINE_VALUE6
findbugs NP_DEREFERENCE_OF_READLINE_VALUECRITICAL
C
findbugs:SC_START_IN_CTOR&
findbugsSC_START_IN_CTORCRITICAL
O
findbugs:WMI_WRONG_MAP_ITERATOR,
findbugsWMI_WRONG_MAP_ITERATORCRITICAL
Z
&findbugs:RV_CHECK_FOR_POSITIVE_INDEXOF0
findbugsRV_CHECK_FOR_POSITIVE_INDEXOFMINOR
\
'findbugs:VO_VOLATILE_REFERENCE_TO_ARRAY1
findbugsVO_VOLATILE_REFERENCE_TO_ARRAYMAJOR
^
(findbugs:AM_CREATES_EMPTY_JAR_FILE_ENTRY2
findbugsAM_CREATES_EMPTY_JAR_FILE_ENTRYMAJOR
f
,findbugs:MS_SHOULD_BE_REFACTORED_TO_BE_FINAL6
findbugs#MS_SHOULD_BE_REFACTORED_TO_BE_FINALMAJOR
<
findbugs:UW_UNCOND_WAIT!
findbugsUW_UNCOND_WAITMAJOR
g
+findbugs:BC_BAD_CAST_TO_CONCRETE_COLLECTION8
findbugs"BC_BAD_CAST_TO_CONCRETE_COLLECTIONCRITICAL
M
findbugs:MWN_MISMATCHED_NOTIFY+
findbugsMWN_MISMATCHED_NOTIFYCRITICAL
s
1findbugs:SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE>
findbugs(SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTECRITICAL
S
!findbugs:SA_LOCAL_SELF_COMPARISON.
findbugsSA_LOCAL_SELF_COMPARISONCRITICAL
R
"findbugs:SE_READ_RESOLVE_IS_STATIC,
findbugsSE_READ_RESOLVE_IS_STATICMAJOR
Z
&findbugs:VA_FORMAT_STRING_USES_NEWLINE0
findbugsVA_FORMAT_STRING_USES_NEWLINEMAJOR
M
findbugs:VO_VOLATILE_INCREMENT+
findbugsVO_VOLATILE_INCREMENTCRITICAL
r
2findbugs:JML_JSR166_CALLING_WAIT_RATHER_THAN_AWAIT<
findbugs)JML_JSR166_CALLING_WAIT_RATHER_THAN_AWAITMAJOR
h
-findbugs:NM_FUTURE_KEYWORD_USED_AS_IDENTIFIER7
findbugs$NM_FUTURE_KEYWORD_USED_AS_IDENTIFIERMAJOR
S
!findbugs:BC_IMPOSSIBLE_INSTANCEOF.
findbugsBC_IMPOSSIBLE_INSTANCEOFCRITICAL
v
4findbugs:DMI_ANNOTATION_IS_NOT_VISIBLE_TO_REFLECTION>
findbugs+DMI_ANNOTATION_IS_NOT_VISIBLE_TO_REFLECTIONMAJOR
_
'findbugs:DMI_INVOKING_HASHCODE_ON_ARRAY4
findbugsDMI_INVOKING_HASHCODE_ON_ARRAYCRITICAL
[
%findbugs:IL_CONTAINER_ADDED_TO_ITSELF2
findbugsIL_CONTAINER_ADDED_TO_ITSELFCRITICAL
v
4findbugs:BX_UNBOXED_AND_COERCED_FOR_TERNARY_OPERATOR>
findbugs+BX_UNBOXED_AND_COERCED_FOR_TERNARY_OPERATORMAJOR
X
%findbugs:NP_SYNC_AND_NULL_CHECK_FIELD/
findbugsNP_SYNC_AND_NULL_CHECK_FIELDMAJOR
<
findbugs:DM_STRING_CTOR!
findbugsDM_STRING_CTORMAJOR
I
findbugs:IC_INIT_CIRCULARITY)
findbugsIC_INIT_CIRCULARITYCRITICAL
M
findbugs:IJU_TEARDOWN_NO_SUPER+
findbugsIJU_TEARDOWN_NO_SUPERCRITICAL
L
findbugs:NP_BOOLEAN_RETURN_NULL)
findbugsNP_BOOLEAN_RETURN_NULLMAJOR
Y
$findbugs:DB_DUPLICATE_SWITCH_CLAUSES1
findbugsDB_DUPLICATE_SWITCH_CLAUSESCRITICAL
l
/findbugs:NP_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD9
findbugs&NP_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELDMAJOR
.
findbugs:DMI_DOH
findbugsDMI_DOHMAJOR
‡
;findbugs:J2EE_STORE_OF_NON_SERIALIZABLE_OBJECT_INTO_SESSIONH
findbugs2J2EE_STORE_OF_NON_SERIALIZABLE_OBJECT_INTO_SESSIONCRITICAL
G
findbugs:UL_UNRELEASED_LOCK(
findbugsUL_UNRELEASED_LOCKCRITICAL
X
$findbugs:DMI_BLOCKING_METHODS_ON_URL0
findbugsDMI_BLOCKING_METHODS_ON_URLBLOCKER
i
,findbugs:QBA_QUESTIONABLE_BOOLEAN_ASSIGNMENT9
findbugs#QBA_QUESTIONABLE_BOOLEAN_ASSIGNMENTCRITICAL
j
.findbugs:ES_COMPARING_PARAMETER_STRING_WITH_EQ8
findbugs%ES_COMPARING_PARAMETER_STRING_WITH_EQMAJOR
m
.findbugs:IM_AVERAGE_COMPUTATION_COULD_OVERFLOW;
findbugs%IM_AVERAGE_COMPUTATION_COULD_OVERFLOWCRITICAL
h
-findbugs:RV_RETURN_VALUE_IGNORED_BAD_PRACTICE7
findbugs$RV_RETURN_VALUE_IGNORED_BAD_PRACTICEMAJOR
^
(findbugs:SE_TRANSIENT_FIELD_NOT_RESTORED2
findbugsSE_TRANSIENT_FIELD_NOT_RESTOREDMAJOR
~
8findbugs:AT_OPERATION_SEQUENCE_ON_CONCURRENT_ABSTRACTIONB
findbugs/AT_OPERATION_SEQUENCE_ON_CONCURRENT_ABSTRACTIONMAJOR
W
#findbugs:ODR_OPEN_DATABASE_RESOURCE0
findbugsODR_OPEN_DATABASE_RESOURCECRITICAL
q
0findbugs:XSS_REQUEST_PARAMETER_TO_SERVLET_WRITER=
findbugs'XSS_REQUEST_PARAMETER_TO_SERVLET_WRITERCRITICAL
>
findbugs:DM_BOOLEAN_CTOR"
findbugsDM_BOOLEAN_CTORMAJOR
z
6findbugs:EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS@
findbugs-EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THISMAJOR
?
findbugs:NP_ALWAYS_NULL$
findbugsNP_ALWAYS_NULLCRITICAL
X
%findbugs:ES_COMPARING_STRINGS_WITH_EQ/
findbugsES_COMPARING_STRINGS_WITH_EQMAJOR
X
%findbugs:ISC_INSTANTIATE_STATIC_CLASS/
findbugsISC_INSTANTIATE_STATIC_CLASSMAJOR
H
findbugs:MF_CLASS_MASKS_FIELD'
findbugsMF_CLASS_MASKS_FIELDMAJOR
}
6findbugs:DMI_COLLECTIONS_SHOULD_NOT_CONTAIN_THEMSELVESC
findbugs-DMI_COLLECTIONS_SHOULD_NOT_CONTAIN_THEMSELVESCRITICAL
C
findbugs:IL_INFINITE_LOOP&
findbugsIL_INFINITE_LOOPCRITICAL
y
4findbugs:STCAL_INVOKE_ON_STATIC_DATE_FORMAT_INSTANCEA
findbugs+STCAL_INVOKE_ON_STATIC_DATE_FORMAT_INSTANCECRITICAL
N
 findbugs:RI_REDUNDANT_INTERFACES*
findbugsRI_REDUNDANT_INTERFACESMAJOR
a
(findbugs:RV_ABSOLUTE_VALUE_OF_RANDOM_INT5
findbugsRV_ABSOLUTE_VALUE_OF_RANDOM_INTCRITICAL
v
4findbugs:SE_TRANSIENT_FIELD_OF_NONSERIALIZABLE_CLASS>
findbugs+SE_TRANSIENT_FIELD_OF_NONSERIALIZABLE_CLASSMAJOR
<
findbugs:SE_INNER_CLASS!
findbugsSE_INNER_CLASSMAJOR
I
findbugs:WS_WRITEOBJECT_SYNC)
findbugsWS_WRITEOBJECT_SYNCCRITICAL
M
findbugs:DMI_EMPTY_DB_PASSWORD+
findbugsDMI_EMPTY_DB_PASSWORDCRITICAL
g
+findbugs:MTIA_SUSPECT_STRUTS_INSTANCE_FIELD8
findbugs"MTIA_SUSPECT_STRUTS_INSTANCE_FIELDCRITICAL
d
+findbugs:SE_READ_RESOLVE_MUST_RETURN_OBJECT5
findbugs"SE_READ_RESOLVE_MUST_RETURN_OBJECTMAJOR
“
Afindbugs:SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRINGN
findbugs8SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRINGCRITICAL
:
findbugs:DE_MIGHT_DROP 
findbugsDE_MIGHT_DROPMAJOR
@
findbugs:ESync_EMPTY_SYNC#
findbugsESync_EMPTY_SYNCMAJOR
i
,findbugs:MTIA_SUSPECT_SERVLET_INSTANCE_FIELD9
findbugs#MTIA_SUSPECT_SERVLET_INSTANCE_FIELDCRITICAL
B
findbugs:DM_FP_NUMBER_CTOR$
findbugsDM_FP_NUMBER_CTORMAJOR
O
findbugs:ICAST_BAD_SHIFT_AMOUNT,
findbugsICAST_BAD_SHIFT_AMOUNTCRITICAL
F
findbugs:SS_SHOULD_BE_STATIC&
findbugsSS_SHOULD_BE_STATICMAJOR
M
findbugs:DMI_USELESS_SUBSTRING+
findbugsDMI_USELESS_SUBSTRINGCRITICAL
@
findbugs:MS_MUTABLE_ARRAY#
findbugsMS_MUTABLE_ARRAYMAJOR
D
findbugs:IT_NO_SUCH_ELEMENT%
findbugsIT_NO_SUCH_ELEMENTMINOR
B
findbugs:NM_VERY_CONFUSING$
findbugsNM_VERY_CONFUSINGMAJOR
S
!findbugs:VA_FORMAT_STRING_ILLEGAL.
findbugsVA_FORMAT_STRING_ILLEGALCRITICAL
1
findbugs:BIT_IOR
findbugsBIT_IORCRITICAL
F
findbugs:EQ_OTHER_USE_OBJECT&
findbugsEQ_OTHER_USE_OBJECTMAJOR
]
&findbugs:RV_ABSOLUTE_VALUE_OF_HASHCODE3
findbugsRV_ABSOLUTE_VALUE_OF_HASHCODECRITICAL
a
(findbugs:DLS_DEAD_STORE_OF_CLASS_LITERAL5
findbugsDLS_DEAD_STORE_OF_CLASS_LITERALCRITICAL
W
#findbugs:SA_LOCAL_DOUBLE_ASSIGNMENT0
findbugsSA_LOCAL_DOUBLE_ASSIGNMENTCRITICAL
u
2findbugs:TQ_NEVER_VALUE_USED_WHERE_ALWAYS_REQUIRED?
findbugs)TQ_NEVER_VALUE_USED_WHERE_ALWAYS_REQUIREDCRITICAL
^
(findbugs:RV_NEGATING_RESULT_OF_COMPARETO2
findbugsRV_NEGATING_RESULT_OF_COMPARETOMINOR
s
1findbugs:TQ_MAYBE_SOURCE_VALUE_REACHES_NEVER_SINK>
findbugs(TQ_MAYBE_SOURCE_VALUE_REACHES_NEVER_SINKCRITICAL
n
0findbugs:VA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSED:
findbugs'VA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSEDMAJOR
c
)findbugs:FE_TEST_IF_EQUAL_TO_NOT_A_NUMBER6
findbugs FE_TEST_IF_EQUAL_TO_NOT_A_NUMBERCRITICAL
q
0findbugs:ICAST_QUESTIONABLE_UNSIGNED_RIGHT_SHIFT=
findbugs'ICAST_QUESTIONABLE_UNSIGNED_RIGHT_SHIFTCRITICAL
n
0findbugs:UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD:
findbugs'UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELDMINOR
d
*findbugs:BC_IMPOSSIBLE_DOWNCAST_OF_TOARRAY6
findbugs!BC_IMPOSSIBLE_DOWNCAST_OF_TOARRAYBLOCKER
`
)findbugs:RV_RETURN_VALUE_IGNORED_INFERRED3
findbugs RV_RETURN_VALUE_IGNORED_INFERREDMINOR
8
findbugs:RV_01_TO_INT
findbugsRV_01_TO_INTMAJOR
W
#findbugs:SIO_SUPERFLUOUS_INSTANCEOF0
findbugsSIO_SUPERFLUOUS_INSTANCEOFCRITICAL
d
+findbugs:BC_BAD_CAST_TO_ABSTRACT_COLLECTION5
findbugs"BC_BAD_CAST_TO_ABSTRACT_COLLECTIONMAJOR
q
0findbugs:ICAST_INT_CAST_TO_FLOAT_PASSED_TO_ROUND=
findbugs'ICAST_INT_CAST_TO_FLOAT_PASSED_TO_ROUNDCRITICAL
S
!findbugs:ITA_INEFFICIENT_TO_ARRAY.
findbugsITA_INEFFICIENT_TO_ARRAYCRITICAL
k
-findbugs:RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSION:
findbugs$RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSIONCRITICAL
I
findbugs:MWN_MISMATCHED_WAIT)
findbugsMWN_MISMATCHED_WAITCRITICAL
s
1findbugs:STCAL_STATIC_SIMPLE_DATE_FORMAT_INSTANCE>
findbugs(STCAL_STATIC_SIMPLE_DATE_FORMAT_INSTANCECRITICAL
‚
:findbugs:VA_FORMAT_STRING_EXPECTED_MESSAGE_FORMAT_SUPPLIEDD
findbugs1VA_FORMAT_STRING_EXPECTED_MESSAGE_FORMAT_SUPPLIEDMAJOR
Y
$findbugs:NP_LOAD_OF_KNOWN_NULL_VALUE1
findbugsNP_LOAD_OF_KNOWN_NULL_VALUECRITICAL
W
#findbugs:NP_NONNULL_PARAM_VIOLATION0
findbugsNP_NONNULL_PARAM_VIOLATIONCRITICAL
O
findbugs:BIT_ADD_OF_SIGNED_BYTE,
findbugsBIT_ADD_OF_SIGNED_BYTECRITICAL
Z
&findbugs:FI_PUBLIC_SHOULD_BE_PROTECTED0
findbugsFI_PUBLIC_SHOULD_BE_PROTECTEDMAJOR
P
!findbugs:SE_BAD_FIELD_INNER_CLASS+
findbugsSE_BAD_FIELD_INNER_CLASSMINOR
m
.findbugs:DL_SYNCHRONIZATION_ON_SHARED_CONSTANT;
findbugs%DL_SYNCHRONIZATION_ON_SHARED_CONSTANTCRITICAL
G
findbugs:GC_UNRELATED_TYPES(
findbugsGC_UNRELATED_TYPESCRITICAL
I
findbugs:LI_LAZY_INIT_STATIC)
findbugsLI_LAZY_INIT_STATICCRITICAL
D
findbugs:MS_SHOULD_BE_FINAL%
findbugsMS_SHOULD_BE_FINALMAJOR
\
'findbugs:RC_REF_COMPARISON_BAD_PRACTICE1
findbugsRC_REF_COMPARISON_BAD_PRACTICEMAJOR
G
findbugs:RV_REM_OF_HASHCODE(
findbugsRV_REM_OF_HASHCODECRITICAL
p
1findbugs:UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR;
findbugs(UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTORMINOR
‡
;findbugs:RCN_REDUNDANT_COMPARISON_OF_NULL_AND_NONNULL_VALUEH
findbugs2RCN_REDUNDANT_COMPARISON_OF_NULL_AND_NONNULL_VALUECRITICAL
T
#findbugs:SE_NO_SUITABLE_CONSTRUCTOR-
findbugsSE_NO_SUITABLE_CONSTRUCTORMAJOR
[
%findbugs:DLS_DEAD_LOCAL_STORE_OF_NULL2
findbugsDLS_DEAD_LOCAL_STORE_OF_NULLCRITICAL
W
#findbugs:HE_USE_OF_UNHASHABLE_CLASS0
findbugsHE_USE_OF_UNHASHABLE_CLASSCRITICAL
U
"findbugs:SA_FIELD_SELF_COMPUTATION/
findbugsSA_FIELD_SELF_COMPUTATIONCRITICAL
]
&findbugs:VA_FORMAT_STRING_BAD_ARGUMENT3
findbugsVA_FORMAT_STRING_BAD_ARGUMENTCRITICAL
]
&findbugs:DMI_CALLING_NEXT_FROM_HASNEXT3
findbugsDMI_CALLING_NEXT_FROM_HASNEXTCRITICAL
T
#findbugs:NM_FIELD_NAMING_CONVENTION-
findbugsNM_FIELD_NAMING_CONVENTIONMAJOR
i
,findbugs:SBSC_USE_STRINGBUFFER_CONCATENATION9
findbugs#SBSC_USE_STRINGBUFFER_CONCATENATIONCRITICAL
M
findbugs:BC_VACUOUS_INSTANCEOF+
findbugsBC_VACUOUS_INSTANCEOFCRITICAL
;
findbugs:IJU_NO_TESTS"
findbugsIJU_NO_TESTSCRITICAL
G
findbugs:IJU_SETUP_NO_SUPER(
findbugsIJU_SETUP_NO_SUPERCRITICAL
u
2findbugs:INT_BAD_COMPARISON_WITH_NONNEGATIVE_VALUE?
findbugs)INT_BAD_COMPARISON_WITH_NONNEGATIVE_VALUECRITICAL
@
findbugs:SP_SPIN_ON_FIELD#
findbugsSP_SPIN_ON_FIELDMAJOR
‹
=findbugs:TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_ALWAYS_SINKJ
findbugs4TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_ALWAYS_SINKCRITICAL
e
*findbugs:VA_FORMAT_STRING_MISSING_ARGUMENT7
findbugs!VA_FORMAT_STRING_MISSING_ARGUMENTCRITICAL
^
(findbugs:BX_UNBOXING_IMMEDIATELY_REBOXED2
findbugsBX_UNBOXING_IMMEDIATELY_REBOXEDMAJOR
R
"findbugs:DM_NEXTINT_VIA_NEXTDOUBLE,
findbugsDM_NEXTINT_VIA_NEXTDOUBLEMAJOR
S
!findbugs:SA_FIELD_SELF_ASSIGNMENT.
findbugsSA_FIELD_SELF_ASSIGNMENTCRITICAL
i
,findbugs:ICAST_INTEGER_MULTIPLY_CAST_TO_LONG9
findbugs#ICAST_INTEGER_MULTIPLY_CAST_TO_LONGCRITICAL
T
#findbugs:SIC_INNER_SHOULD_BE_STATIC-
findbugsSIC_INNER_SHOULD_BE_STATICMAJOR
B
findbugs:CO_SELF_NO_OBJECT$
findbugsCO_SELF_NO_OBJECTMAJOR
?
findbugs:OS_OPEN_STREAM$
findbugsOS_OPEN_STREAMCRITICAL
=
findbugs:DM_CONVERT_CASE!
findbugsDM_CONVERT_CASEINFO
]
&findbugs:VA_FORMAT_STRING_ARG_MISMATCH3
findbugsVA_FORMAT_STRING_ARG_MISMATCHCRITICAL
L
findbugs:NM_CLASS_NOT_EXCEPTION)
findbugsNM_CLASS_NOT_EXCEPTIONMAJOR
p
1findbugs:PZ_DONT_REUSE_ENTRY_OBJECTS_IN_ITERATORS;
findbugs(PZ_DONT_REUSE_ENTRY_OBJECTS_IN_ITERATORSMAJOR
q
0findbugs:DMI_USING_REMOVEALL_TO_CLEAR_COLLECTION=
findbugs'DMI_USING_REMOVEALL_TO_CLEAR_COLLECTIONCRITICAL
H
findbugs:IMSE_DONT_CATCH_IMSE'
findbugsIMSE_DONT_CATCH_IMSEMAJOR
Y
$findbugs:NP_STORE_INTO_NONNULL_FIELD1
findbugsNP_STORE_INTO_NONNULL_FIELDCRITICAL
]
&findbugs:DL_SYNCHRONIZATION_ON_BOOLEAN3
findbugsDL_SYNCHRONIZATION_ON_BOOLEANCRITICAL
R
"findbugs:EQ_DOESNT_OVERRIDE_EQUALS,
findbugsEQ_DOESNT_OVERRIDE_EQUALSMAJOR
H
findbugs:IS_INCONSISTENT_SYNC'
findbugsIS_INCONSISTENT_SYNCMAJOR
‚
:findbugs:IC_SUPERCLASS_USES_SUBCLASS_DURING_INITIALIZATIOND
findbugs1IC_SUPERCLASS_USES_SUBCLASS_DURING_INITIALIZATIONMAJOR
O
findbugs:INT_VACUOUS_COMPARISON,
findbugsINT_VACUOUS_COMPARISONCRITICAL
l
/findbugs:RV_RETURN_VALUE_OF_PUTIFABSENT_IGNORED9
findbugs&RV_RETURN_VALUE_OF_PUTIFABSENT_IGNOREDMAJOR
I
findbugs:UM_UNNECESSARY_MATH)
findbugsUM_UNNECESSARY_MATHCRITICAL
{
5findbugs:BC_EQUALS_METHOD_SHOULD_WORK_FOR_ALL_OBJECTSB
findbugs,BC_EQUALS_METHOD_SHOULD_WORK_FOR_ALL_OBJECTSCRITICAL
0
findbugs:CN_IDIOM
findbugsCN_IDIOMMAJOR
C
findbugs:FI_NULLIFY_SUPER&
findbugsFI_NULLIFY_SUPERCRITICAL
H
findbugs:NP_GUARANTEED_DEREF(
findbugsNP_GUARANTEED_DEREFBLOCKER
k
-findbugs:NP_IMMEDIATE_DEREFERENCE_OF_READLINE:
findbugs$NP_IMMEDIATE_DEREFERENCE_OF_READLINECRITICAL
j
.findbugs:SE_PRIVATE_READ_RESOLVE_NOT_INHERITED8
findbugs%SE_PRIVATE_READ_RESOLVE_NOT_INHERITEDMAJOR
<
findbugs:EI_EXPOSE_REP2!
findbugsEI_EXPOSE_REP2MAJOR
S
!findbugs:SA_FIELD_SELF_COMPARISON.
findbugsSA_FIELD_SELF_COMPARISONCRITICAL
K
findbugs:WA_AWAIT_NOT_IN_LOOP*
findbugsWA_AWAIT_NOT_IN_LOOPCRITICAL
d
+findbugs:EQ_OVERRIDING_EQUALS_NOT_SYMMETRIC5
findbugs"EQ_OVERRIDING_EQUALS_NOT_SYMMETRICMAJOR
4
findbugs:EQ_UNUSUAL
findbugs
EQ_UNUSUALMINOR
Q
 findbugs:RV_EXCEPTION_NOT_THROWN-
findbugsRV_EXCEPTION_NOT_THROWNCRITICAL
X
%findbugs:SE_NONSTATIC_SERIALVERSIONID/
findbugsSE_NONSTATIC_SERIALVERSIONIDMAJOR
…
:findbugs:HE_SIGNATURE_DECLARES_HASHING_OF_UNHASHABLE_CLASSG
findbugs1HE_SIGNATURE_DECLARES_HASHING_OF_UNHASHABLE_CLASSCRITICAL
b
*findbugs:INT_BAD_COMPARISON_WITH_INT_VALUE4
findbugs!INT_BAD_COMPARISON_WITH_INT_VALUEMAJOR
m
.findbugs:VA_FORMAT_STRING_NO_PREVIOUS_ARGUMENT;
findbugs%VA_FORMAT_STRING_NO_PREVIOUS_ARGUMENTCRITICAL
:
findbugs:MS_PKGPROTECT 
findbugsMS_PKGPROTECTMAJOR
<
findbugs:UR_UNINIT_READ!
findbugsUR_UNINIT_READMAJOR
Q
 findbugs:NO_NOTIFY_NOT_NOTIFYALL-
findbugsNO_NOTIFY_NOT_NOTIFYALLCRITICAL
z
6findbugs:ML_SYNC_ON_FIELD_TO_GUARD_CHANGING_THAT_FIELD@
findbugs-ML_SYNC_ON_FIELD_TO_GUARD_CHANGING_THAT_FIELDMAJOR
V
$pmd:AvoidFieldNameMatchingMethodName.
pmd AvoidFieldNameMatchingMethodNameMAJOR
M
pmd:ExcessivePublicCount1
pmdExcessivePublicCountMAJOR"
minimum90
P
!pmd:UnnecessaryFullyQualifiedName+
pmdUnnecessaryFullyQualifiedNameMAJOR
N
 pmd:UnnecessaryLocalBeforeReturn*
pmdUnnecessaryLocalBeforeReturnMAJOR
Y
pmd:TooManyStaticImports=
pmdTooManyStaticImportsMAJOR"
maximumStaticImports4
F
pmd:CompareObjectsWithEquals&
pmdCompareObjectsWithEqualsMAJOR
P
!pmd:ConsecutiveAppendsShouldReuse+
pmdConsecutiveAppendsShouldReuseMAJOR
4
pmd:UseArraysAsList
pmdUseArraysAsListMAJOR
@
pmd:UnusedFormalParameter#
pmdUnusedFormalParameterMAJOR
\
'pmd:InsufficientStringBufferDeclaration1
pmd#InsufficientStringBufferDeclarationMAJOR
z
pmd:UncommentedEmptyConstructorW
pmdUncommentedEmptyConstructorMAJOR",
#ignoreExplicitConstructorInvocationfalse
E
pmd:UnnecessaryFinalModifier%
pmdUnnecessaryFinalModifierINFO
A
pmd:UseProperClassLoader%
pmdUseProperClassLoaderCRITICAL
&
pmd:GodClass
pmdGodClassMAJOR
D
pmd:BigIntegerInstantiation%
pmdBigIntegerInstantiationMAJOR
b
pmd:BooleanGetMethodNameF
pmdBooleanGetMethodNameMAJOR""
checkParameterizedMethodsfalse
R
"pmd:AvoidSynchronizedAtMethodLevel,
pmdAvoidSynchronizedAtMethodLevelMAJOR
8
pmd:UnnecessaryReturn
pmdUnnecessaryReturnMINOR
2
pmd:CheckResultSet
pmdCheckResultSetMAJOR
2
pmd:StringToString
pmdStringToStringMAJOR
D
pmd:AccessorClassGeneration%
pmdAccessorClassGenerationMAJOR
A
pmd:TooManyFields,
pmdTooManyFieldsMAJOR"
	maxfields15
0
pmd:ExtendsObject
pmdExtendsObjectMINOR
J
pmd:InefficientStringBuffering(
pmdInefficientStringBufferingMAJOR
T
#pmd:AvoidProtectedFieldInFinalClass-
pmdAvoidProtectedFieldInFinalClassMAJOR
<
pmd:DoNotHardCodeSDCard!
pmdDoNotHardCodeSDCardMAJOR
*
pmd:UseVarargs
pmd
UseVarargsMAJOR
X
%pmd:AvoidThrowingNullPointerException/
pmd!AvoidThrowingNullPointerExceptionMAJOR
:
pmd:AvoidUsingVolatile 
pmdAvoidUsingVolatileMAJOR
2
pmd:UseIndexOfChar
pmdUseIndexOfCharMAJOR
0
pmd:SingularField
pmdSingularFieldMINOR
L
pmd:SimpleDateFormatNeedsLocale)
pmdSimpleDateFormatNeedsLocaleMAJOR
N
 pmd:AvoidAccessibilityAlteration*
pmdAvoidAccessibilityAlterationMAJOR
4
pmd:DoNotUseThreads
pmdDoNotUseThreadsMAJOR
=
pmd:MisplacedNullCheck#
pmdMisplacedNullCheckCRITICAL
B
pmd:UnnecessaryConstructor$
pmdUnnecessaryConstructorMAJOR
>
pmd:LoosePackageCoupling"
pmdLoosePackageCouplingMAJOR
B
pmd:ShortMethodName+
pmdShortMethodNameMAJOR"
minimum3
@
pmd:ShortClassName*
pmdShortClassNameMINOR"
minimum5
2
pmd:CommentContent
pmdCommentContentMINOR
B
pmd:AvoidStringBufferField$
pmdAvoidStringBufferFieldMAJOR
C
pmd:ArrayIsStoredDirectly&
pmdArrayIsStoredDirectlyCRITICAL
2
pmd:LogicInversion
pmdLogicInversionMINOR
L
pmd:UseNotifyAllInsteadOfNotify)
pmdUseNotifyAllInsteadOfNotifyMAJOR
4
pmd:AvoidArrayLoops
pmdAvoidArrayLoopsMAJOR
>
pmd:AvoidUsingNativeCode"
pmdAvoidUsingNativeCodeMAJOR
>
pmd:BooleanInstantiation"
pmdBooleanInstantiationMAJOR
€
pmd:NonThreadSafeSingletonb
pmdNonThreadSafeSingletonMAJOR"
checkNonStaticMethodstrue"
checkNonStaticFieldsfalse
d
+pmd:AvoidThrowingNewInstanceOfSameException5
pmd'AvoidThrowingNewInstanceOfSameExceptionMAJOR
D
pmd:MissingSerialVersionUID%
pmdMissingSerialVersionUIDMAJOR
<
pmd:SimplifyConditional!
pmdSimplifyConditionalMAJOR
O
pmd:UselessOperationOnImmutable,
pmdUselessOperationOnImmutableCRITICAL
D
pmd:AppendCharacterWithChar%
pmdAppendCharacterWithCharMINOR
8
pmd:LongInstantiation
pmdLongInstantiationMAJOR
A
pmd:NcssTypeCount,
pmdNcssTypeCountMAJOR"
minimum1500
L
pmd:InefficientEmptyStringCheck)
pmdInefficientEmptyStringCheckMAJOR
j
.pmd:EmptyMethodInAbstractClassShouldBeAbstract8
pmd*EmptyMethodInAbstractClassShouldBeAbstractMAJOR
2
pmd:ImmutableField
pmdImmutableFieldMAJOR
:
pmd:SimplifyStartsWith 
pmdSimplifyStartsWithMINOR
P
!pmd:ClassCastExceptionWithToArray+
pmdClassCastExceptionWithToArrayMAJOR
B
pmd:OptimizableToArrayCall$
pmdOptimizableToArrayCallMAJOR
D
pmd:UnusedNullCheckInEquals%
pmdUnusedNullCheckInEqualsMAJOR
P
!pmd:AbstractClassWithoutAnyMethod+
pmdAbstractClassWithoutAnyMethodMAJOR
>
pmd:PrematureDeclaration"
pmdPrematureDeclarationMAJOR
0
pmd:CallSuperLast
pmdCallSuperLastMAJOR
J
pmd:AssignmentToNonFinalStatic(
pmdAssignmentToNonFinalStaticMAJOR
7
pmd:BrokenNullCheck 
pmdBrokenNullCheckCRITICAL
H
pmd:LocalHomeNamingConvention'
pmdLocalHomeNamingConventionMAJOR
V
$pmd:UnnecessaryWrapperObjectCreation.
pmd UnnecessaryWrapperObjectCreationMAJOR
@
pmd:SuspiciousOctalEscape#
pmdSuspiciousOctalEscapeMAJOR
:
pmd:ShortInstantiation 
pmdShortInstantiationMAJOR
T
#pmd:UseStringBufferForStringAppends-
pmdUseStringBufferForStringAppendsMAJOR
\
'pmd:AvoidBranchingStatementAsLastInLoop1
pmd#AvoidBranchingStatementAsLastInLoopMAJOR
<
pmd:StringInstantiation!
pmdStringInstantiationMAJOR
D
pmd:InstantiationToGetClass%
pmdInstantiationToGetClassMAJOR
X
%pmd:ConstructorCallsOverridableMethod/
pmd!ConstructorCallsOverridableMethodMAJOR
`
)pmd:LocalInterfaceSessionNamingConvention3
pmd%LocalInterfaceSessionNamingConventionMAJOR
R
"pmd:DontUseFloatTypeForLoopIndices,
pmdDontUseFloatTypeForLoopIndicesMAJOR
p
1pmd:ClassWithOnlyPrivateConstructorsShouldBeFinal;
pmd-ClassWithOnlyPrivateConstructorsShouldBeFinalMAJOR
R
"pmd:AvoidFieldNameMatchingTypeName,
pmdAvoidFieldNameMatchingTypeNameMAJOR
T
#pmd:RemoteInterfaceNamingConvention-
pmdRemoteInterfaceNamingConventionMAJOR
L
pmd:StaticEJBFieldShouldBeFinal)
pmdStaticEJBFieldShouldBeFinalMAJOR
2
pmd:CallSuperFirst
pmdCallSuperFirstMAJOR
4
pmd:CheckSkipResult
pmdCheckSkipResultMINOR
2
pmd:EmptyFinalizer
pmdEmptyFinalizerMAJOR
0
pmd:BadComparison
pmdBadComparisonMAJOR
@
pmd:UseStringBufferLength#
pmdUseStringBufferLengthMINOR
8
pmd:ByteInstantiation
pmdByteInstantiationMAJOR
l
/pmd:MissingStaticMethodInNonInstantiatableClass9
pmd+MissingStaticMethodInNonInstantiatableClassMAJOR
F
pmd:ForLoopShouldBeWhileLoop&
pmdForLoopShouldBeWhileLoopMINOR
B
pmd:UseObjectForClearerAPI$
pmdUseObjectForClearerAPIMINOR
n
0pmd:AvoidProtectedMethodInFinalClassNotExtending:
pmd,AvoidProtectedMethodInFinalClassNotExtendingMAJOR
b
*pmd:RemoteSessionInterfaceNamingConvention4
pmd&RemoteSessionInterfaceNamingConventionMAJOR
>
pmd:DoubleCheckedLocking"
pmdDoubleCheckedLockingMAJOR
X
%pmd:MDBAndSessionBeanNamingConvention/
pmd!MDBAndSessionBeanNamingConventionMAJOR
X
%pmd:UnsynchronizedStaticDateFormatter/
pmd!UnsynchronizedStaticDateFormatterMAJOR
F
common-java:DuplicatedBlocks&
common-javaDuplicatedBlocksMAJOR
~
&common-java:InsufficientBranchCoverageT
common-javaInsufficientBranchCoverageMAJOR""
minimumBranchCoverageRatio65.0